import mlx.core as mx, numpy as np, pathlib, json, sys
L=int(sys.argv[1]); root=pathlib.Path(sys.argv[2] if len(sys.argv)>2 else '/Users/mikuru/qwen38fn-official-pipeline/output/Qwen3.8-Flash-Next-OurAblit-Mixed-MLX-Serve'); M=json.load(open(sys.argv[3] if len(sys.argv)>3 else '/Users/mikuru/qwen-native-runtime/phase0/qwen38fn_manifest.json'))['tensors']; p=f'language_model.model.layers.{L}.'
need=[n for n in M if n.startswith(p) and ('.attn_hyper_connection.' in n or '.linear_attn.' in n)]
shards={M[n]['shard'] for n in need}; A={}
for sh in shards:A.update(mx.load(str(root/sh)))
rng=np.random.default_rng(500000+L); h=(rng.standard_normal(10240)*.07).astype(np.float32); conv=(rng.standard_normal((10240,4))*.03).astype(np.float32); S=(rng.standard_normal((48,128,128))*.005).astype(np.float32)
def qmm(base,x):return np.array(mx.quantized_matmul(mx.array(x),A[base+'.weight'],A[base+'.scales'],A[base+'.biases'],group_size=64,bits=8),np.float32)
def bf(n):return np.array(A[n].astype(mx.float32),np.float32)
xn=h.reshape(4,2560);xn=xn/np.sqrt(np.mean(xn*xn,-1,keepdims=True)+1e-6)*bf(p+'attn_hyper_connection.hc_norm.weight').reshape(4,2560);xf=xn.reshape(-1);d=qmm(p+'attn_hyper_connection.input_mix_weight_down',xf)/4;d=d/(1+np.exp(-d));mw=1/(1+np.exp(-qmm(p+'attn_hyper_connection.input_mix_weight_up',d)));mixed=(xf.reshape(4,2560)*mw.reshape(4,2560)).mean(0);iw=bf(p+'attn_hyper_connection.block_inject_weight.weight').reshape(4,10240);inj=2/(1+np.exp(-(iw@xf)/4))
qkv=qmm(p+'linear_attn.in_proj_qkv',mixed);z=qmm(p+'linear_attn.in_proj_z',mixed).reshape(48,128);aa=qmm(p+'linear_attn.in_proj_a',mixed);bb=qmm(p+'linear_attn.in_proj_b',mixed);cw=bf(p+'linear_attn.conv1d.weight').reshape(10240,4);cat=np.concatenate([conv,qkv[:,None]],1);cv=(cat[:,1:5]*cw).sum(1);cv=cv/(1+np.exp(-cv));conv2=cat[:,-4:]
q=np.repeat(cv[:2048].reshape(16,128),3,0);k=np.repeat(cv[2048:4096].reshape(16,128),3,0);v=cv[4096:].reshape(48,128);q=q/np.sqrt(np.sum(q*q,-1,keepdims=True)+1e-6);k=k/np.sqrt(np.sum(k*k,-1,keepdims=True)+1e-6);beta=1/(1+np.exp(-bb));g=-np.exp(bf(p+'linear_attn.A_log'))*np.logaddexp(0,aa+bf(p+'linear_attn.dt_bias'));S2=S*np.exp(g)[:,None,None];dv=(v-np.einsum('hkv,hk->hv',S2,k))*beta[:,None];S2+=k[:,:,None]*dv[:,None,:];core=np.einsum('hk,hkv->hv',q/np.sqrt(128),S2);core=core/np.sqrt(np.mean(core*core,-1,keepdims=True)+1e-6)*bf(p+'linear_attn.norm.weight')[None,:];core*=1/(1+np.exp(-z));att=qmm(p+'linear_attn.out_proj',core.reshape(-1));final=(h.reshape(4,2560)+inj[:,None]*att[None,:]).astype(np.float32).reshape(-1)
P=pathlib.Path(f'/tmp/qn_gdn_L{L:02d}');P.mkdir(exist_ok=True)
for n,x in [('hyper',h),('conv',conv),('state',S),('conv_state_out',conv2),('state_out',S2),('final',final)]:np.asarray(x,np.float32).tofile(P/(n+'.bin'))
print('L',L,'shards',sorted(shards),'final0',float(final[0]))
