#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "../qn_runtime.h"
#include <mach/mach_time.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
static double ms(){static mach_timebase_info_data_t t;if(!t.denom)mach_timebase_info(&t);return(double)mach_absolute_time()*t.numer/t.denom/1e6;}
int main(){@autoreleasepool{
 const char*model=getenv("QWEN4_TEST_MODEL"); if(!model){fprintf(stderr,"QWEN4_TEST_MODEL required\n");return 77;} char shp[1400];snprintf(shp,sizeof(shp),"%s/model-00001.safetensors",model);const char*sh=shp; char er[256]; qn_file_map m;
 if(qn_file_map_open(&m,sh,er,sizeof(er))){fprintf(stderr,"map %s\n",er);return 1;}
 qn_affine_desc d={14397432,40611832,41431032,10240,2560,64,8};
 id<MTLDevice>dev=MTLCreateSystemDefaultDevice(); id<MTLCommandQueue>q=[dev newCommandQueue]; qn_affine_metal_view vw;
 if(qn_affine_make_view(dev,&m,&d,&vw,er,sizeof(er))){fprintf(stderr,"view %s\n",er);return 2;}
 NSString*src=@"#include <metal_stdlib>\nusing namespace metal;inline float bf(ushort v){return as_type<float>((uint)v<<16);}kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float s=bf(sc[r*G+g]),b=bf(bi[r*G+g]);uint j=lane>>2,t=(lane&3u)*2u,p=w[r*W+g*16+j],k=g*64+j*8+t;a+=x[k]*((float)((p>>(8*t))&255u)*s+b)+x[k+1]*((float)((p>>(8*(t+1)))&255u)*s+b);}a=simd_sum(a);if(lane==0)y[r]=a;}kernel void q8_rows(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],constant uint&T[[buffer(7)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint z=tid/32,tok=z/O,r=z-tok*O;if(tok>=T)return;device const float*xr=x+tok*I;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float s=bf(sc[r*G+g]),b=bf(bi[r*G+g]);uint j=lane>>2,t=(lane&3u)*2u,p=w[r*W+g*16+j],k=g*64+j*8+t;a+=xr[k]*((float)((p>>(8*t))&255u)*s+b)+xr[k+1]*((float)((p>>(8*(t+1)))&255u)*s+b);}a=simd_sum(a);if(lane==0)y[tok*O+r]=a;}";
 NSError*e=nil; id<MTLLibrary>lib=[dev newLibraryWithSource:src options:nil error:&e]; if(!lib){fprintf(stderr,"lib %s\n",e.description.UTF8String);return 3;} id p1=[dev newComputePipelineStateWithFunction:[lib newFunctionWithName:@"q8_mv"] error:&e], pr=[dev newComputePipelineStateWithFunction:[lib newFunctionWithName:@"q8_rows"] error:&e];
 uint O=10240,I=2560; for(int ci=0;ci<3;ci++){uint T=ci==0?5:ci==1?16:64; size_t xn=(size_t)T*I,yn=(size_t)T*O; float*x=malloc(xn*4);for(size_t i=0;i<xn;i++)x[i]=sinf((float)i*.001f)*.1f; id<MTLBuffer> xb=[dev newBufferWithBytes:x length:xn*4 options:MTLResourceStorageModeShared], y1=[dev newBufferWithLength:yn*4 options:MTLResourceStorageModeShared], yr=[dev newBufferWithLength:yn*4 options:MTLResourceStorageModeShared];
  for(int warm=0;warm<3;warm++){id cb=[q commandBuffer];id ce=[cb computeCommandEncoder];[ce setComputePipelineState:p1];for(uint t=0;t<T;t++){[ce setBuffer:vw.weight offset:0 atIndex:0];[ce setBuffer:vw.scales offset:0 atIndex:1];[ce setBuffer:vw.biases offset:0 atIndex:2];[ce setBuffer:xb offset:(NSUInteger)t*I*4 atIndex:3];[ce setBuffer:y1 offset:(NSUInteger)t*O*4 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}[ce endEncoding];[cb commit];[cb waitUntilCompleted];}
  int it=20;double t0=ms();for(int z=0;z<it;z++){id cb=[q commandBuffer];id ce=[cb computeCommandEncoder];[ce setComputePipelineState:p1];for(uint t=0;t<T;t++){[ce setBuffer:vw.weight offset:0 atIndex:0];[ce setBuffer:vw.scales offset:0 atIndex:1];[ce setBuffer:vw.biases offset:0 atIndex:2];[ce setBuffer:xb offset:(NSUInteger)t*I*4 atIndex:3];[ce setBuffer:y1 offset:(NSUInteger)t*O*4 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}[ce endEncoding];[cb commit];[cb waitUntilCompleted];}double seq=(ms()-t0)/it;
  for(int warm=0;warm<3;warm++){id cb=[q commandBuffer];id ce=[cb computeCommandEncoder];[ce setComputePipelineState:pr];[ce setBuffer:vw.weight offset:0 atIndex:0];[ce setBuffer:vw.scales offset:0 atIndex:1];[ce setBuffer:vw.biases offset:0 atIndex:2];[ce setBuffer:xb offset:0 atIndex:3];[ce setBuffer:yr offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce setBytes:&T length:4 atIndex:7];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];}
  t0=ms();for(int z=0;z<it;z++){id cb=[q commandBuffer];id ce=[cb computeCommandEncoder];[ce setComputePipelineState:pr];[ce setBuffer:vw.weight offset:0 atIndex:0];[ce setBuffer:vw.scales offset:0 atIndex:1];[ce setBuffer:vw.biases offset:0 atIndex:2];[ce setBuffer:xb offset:0 atIndex:3];[ce setBuffer:yr offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce setBytes:&T length:4 atIndex:7];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];}double bat=(ms()-t0)/it;
  float*a=y1.contents,*b=yr.contents;double mx=0,rm=0;for(size_t i=0;i<yn;i++){double z=(double)a[i]-b[i];mx=fmax(mx,fabs(z));rm+=z*z;}printf("T=%u seq=%.4fms batch=%.4fms speedup=%.3fx tok/s(seq)=%.1f tok/s(batch)=%.1f max=%.3g rmse=%.3g\n",T,seq,bat,seq/bat,T*1000/seq,T*1000/bat,mx,sqrt(rm/yn));free(x);
 }
 qn_file_map_close(&m);}}
