#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import "qn_runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
static void*rd(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f){perror("fopen");exit(1);}void*x=malloc(n);if(fread(x,1,n,f)!=n){fprintf(stderr,"short %s\n",p);exit(1);}fclose(f);return x;}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal; inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint row=tid/32;if(row>=512)return;float a=0;device const uint*wr=w+row*640;device const ushort*sr=sc+row*40;device const ushort*br=bi+row*40;for(uint g=0;g<40;g++){float s=bf16f(sr[g]),b=bf16f(br[g]);uint xb=g*64,wb=g*16;for(uint j=lane;j<16;j+=32){uint p=wr[wb+j],k=xb+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);float4 xv=float4(x[k],x[k+1],x[k+2],x[k+3]);a+=dot(xv,q*s+b);}}a=simd_sum(a);if(lane==0)y[row]=a;}
)METAL";}
typedef struct{float p;int i;} Pair;static int cmp(const void*a,const void*b){float x=((Pair*)a)->p,y=((Pair*)b)->p;return x<y?1:x>y?-1:0;}
int main(int ac,char**av){if(ac!=6){fprintf(stderr,"usage: %s shard x logits_ref ids_ref weights_ref\n",av[0]);return 2;}float*x=rd(av[2],2560*4),*lr=rd(av[3],512*4),*wr=rd(av[5],10*4);int*ir=rd(av[4],10*4);char er[256];qn_file_map fm;if(qn_file_map_open(&fm,av[1],er,sizeof(er))){fprintf(stderr,"%s\n",er);return 1;}@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();NSError*e=nil;id<MTLLibrary>lib=[d newLibraryWithSource:src() options:nil error:&e];id<MTLComputePipelineState>ps=[d newComputePipelineStateWithFunction:[lib newFunctionWithName:@"q8_mv"] error:&e];id<MTLCommandQueue>cq=[d newCommandQueue];qn_affine_desc ad={471869896,473180616,473221576,512,2560,64,8};qn_affine_metal_view v={0};if(qn_affine_make_view(d,&fm,&ad,&v,er,sizeof(er))){fprintf(stderr,"%s\n",er);return 1;}id<MTLBuffer>xb=[d newBufferWithBytes:x length:2560*4 options:MTLResourceStorageModeShared],yb=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared];id<MTLCommandBuffer>cb=[cq commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:ps];[ce setBuffer:v.weight offset:0 atIndex:0];[ce setBuffer:v.scales offset:0 atIndex:1];[ce setBuffer:v.biases offset:0 atIndex:2];[ce setBuffer:xb offset:0 atIndex:3];[ce setBuffer:yb offset:0 atIndex:4];[ce dispatchThreads:MTLSizeMake(512*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];float*y=yb.contents;double mx=0,ma=0;float vmax=-INFINITY;for(int i=0;i<512;i++){double z=fabs((double)y[i]-lr[i]);if(z>mx)mx=z;ma+=z;if(y[i]>vmax)vmax=y[i];}Pair a[512];double den=0;for(int i=0;i<512;i++)den+=exp((double)y[i]-vmax);for(int i=0;i<512;i++){a[i].p=(float)(exp((double)y[i]-vmax)/den);a[i].i=i;}qsort(a,512,sizeof(Pair),cmp);int mis=0;double wmax=0,wma=0;printf("native ids");for(int j=0;j<10;j++){printf(" %d",a[j].i);if(a[j].i!=ir[j])mis++;double z=fabs((double)a[j].p-wr[j]);if(z>wmax)wmax=z;wma+=z;}printf("\nref ids   ");for(int j=0;j<10;j++)printf(" %d",ir[j]);printf("\nlogits max=%.6g mae=%.6g route_mismatch=%d weights_max=%.6g weights_mae=%.6g\n",mx,ma/512,mis,wmax,wma/10.0);}
free(x);free(lr);free(ir);free(wr);qn_file_map_close(&fm);return 0;}
