#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import "qn_runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

static void *rd(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f){perror("fopen");exit(1);}void*x=malloc(n);if(fread(x,1,n,f)!=n){fprintf(stderr,"short %s\n",p);exit(1);}fclose(f);return x;}
static void estat(const char*n,const float*a,const float*b,size_t N){double mx=0,ma=0,se=0,dot=0,aa=0,bb=0;for(size_t i=0;i<N;i++){double e=(double)a[i]-b[i],z=fabs(e);if(z>mx)mx=z;ma+=z;se+=e*e;dot+=(double)a[i]*b[i];aa+=(double)a[i]*a[i];bb+=(double)b[i]*b[i];}printf("%s max=%.6g mae=%.6g rmse=%.6g cos=%.12f\n",n,mx,ma/N,sqrt(se/N),dot/sqrt(aa*bb));}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;
inline float bf16f(ushort v){return as_type<float>((uint)v<<16);} inline float sigm(float x){return 1.0f/(1.0f+exp(-x));} inline float rinv(uint j){return pow(10000000.0f,-(2.0f*(float)j)/64.0f);}

kernel void group_rms4(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)y[g*2560+j]=x[g*2560+j]*inv*bf16f(w[g*2560+j]);}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&outdim[[buffer(5)]],constant uint&indim[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint row=tid/32;if(row>=outdim)return;uint groups=indim/64,wcols=indim/4;float acc=0;device const uint*wr=w+row*wcols;device const ushort*sr=sc+row*groups;device const ushort*br=bi+row*groups;for(uint g=0;g<groups;g++){float s=bf16f(sr[g]),b=bf16f(br[g]);uint xb=g*64,wb=g*16;for(uint j=lane;j<16;j+=32){uint p=wr[wb+j],k=xb+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);float4 xv=float4(x[k],x[k+1],x[k+2],x[k+3]);acc+=dot(xv,q*s+b);}}acc=simd_sum(acc);if(lane==0)y[row]=acc;}
kernel void q8_rows(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&outdim[[buffer(5)]],constant uint&indim[[buffer(6)]],constant uint&tokens[[buffer(7)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint gi=tid/32,tok=gi/outdim,row=gi%outdim;if(tok>=tokens)return;uint groups=indim/64,wcols=indim/4;float acc=0;device const uint*wr=w+row*wcols;device const ushort*sr=sc+row*groups;device const ushort*br=bi+row*groups;device const float*xr=x+tok*indim;for(uint g=0;g<groups;g++){float s=bf16f(sr[g]),b=bf16f(br[g]);uint xb=g*64,wb=g*16;for(uint j=lane;j<16;j+=32){uint p=wr[wb+j],k=xb+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);float4 xv=float4(xr[k],xr[k+1],xr[k+2],xr[k+3]);acc+=dot(xv,q*s+b);}}acc=simd_sum(acc);if(lane==0)y[tok*outdim+row]=acc;}
kernel void silu_div4(device float*x[[buffer(0)]],constant uint&n[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<n){float z=x[i]*0.25f;x[i]=z*sigm(z);}}
kernel void sigmoid_ip(device float*x[[buffer(0)]],constant uint&n[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<n)x[i]=sigm(x[i]);}
kernel void mix4(device const float*xnorm[[buffer(0)]],device const float*mixw[[buffer(1)]],device float*out[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<2560){float z=0;for(uint g=0;g<4;g++)z+=xnorm[g*2560+i]*mixw[g*2560+i];out[i]=z*0.25f;}}
kernel void bf16_mv4(device const ushort*w[[buffer(0)]],device const float*x[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint row=tid/32;if(row>=4)return;float a=0;for(uint j=lane;j<10240;j+=32)a+=bf16f(w[row*10240+j])*x[j];a=simd_sum(a);if(lane==0)y[row]=2.0f*sigm(a*0.25f);}
kernel void q_last_norm_rope(device const float*raw[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*out[[buffer(2)]],constant uint&tok[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=4)return;device const float*q=raw+h*128;threadgroup float tmp[128];float ss=0;for(uint j=lane;j<128;j+=32){float z=q[j];tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/128.0f+1e-6f);for(uint j=lane;j<128;j+=32)tmp[j]=tmp[j]*inv*bf16f(w[j]);threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)tok*rinv(j),c=cos(ang),s=sin(ang);tmp[j]=a*c-b*s;tmp[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)out[h*128+j]=tmp[j];}
kernel void kcomp_rope(device const float*raw[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*out[[buffer(2)]],constant uint&blocks[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint block=tid/32;if(block>=blocks)return;threadgroup float tmp[128];float ss=0;for(uint j=lane;j<128;j+=32){float z=0;for(uint t=0;t<4;t++)z+=raw[(block*4+t)*128+j];z*=0.25f;tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/128.0f+1e-6f);for(uint j=lane;j<128;j+=32)tmp[j]=tmp[j]*inv*bf16f(w[j]);threadgroup_barrier(mem_flags::mem_threadgroup);uint pos=block*4;for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);tmp[j]=a*c-b*s;tmp[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)out[block*128+j]=tmp[j];}
kernel void score_blocks(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device float*scores[[buffer(2)]],constant uint&blocks[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint b=tid/32;if(b>=blocks)return;float total=0;for(uint h=0;h<4;h++){float z=0;for(uint j=lane;j<128;j+=32)z+=q[h*128+j]*k[b*128+j];z=simd_sum(z);if(lane==0)total+=max(z,0.0f);}if(lane==0)scores[b]=total*0.08838834764831845f;}
kernel void gated_qkv(device const float*qraw[[buffer(0)]],device const float*kraw[[buffer(1)]],device const float*vraw[[buffer(2)]],device const ushort*qw[[buffer(3)]],device const ushort*kw[[buffer(4)]],device float*qout[[buffer(5)]],device float*gate[[buffer(6)]],device float*kout[[buffer(7)]],device float*vout[[buffer(8)]],constant uint&pos[[buffer(9)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h<24){threadgroup float tmp[256];float ss=0;for(uint j=lane;j<256;j+=32){float z=qraw[h*512+j];tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/256.0f+1e-6f);for(uint j=lane;j<256;j+=32){tmp[j]=tmp[j]*inv*bf16f(qw[j]);gate[h*256+j]=qraw[h*512+256+j];}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);tmp[j]=a*c-b*s;tmp[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<256;j+=32)qout[h*256+j]=tmp[j];}else if(h<26){uint kh=h-24;threadgroup float tmpk[256];float ss=0;for(uint j=lane;j<256;j+=32){float z=kraw[kh*256+j];tmpk[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/256.0f+1e-6f);for(uint j=lane;j<256;j+=32){tmpk[j]=tmpk[j]*inv*bf16f(kw[j]);vout[kh*256+j]=vraw[kh*256+j];}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmpk[j],b=tmpk[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);tmpk[j]=a*c-b*s;tmpk[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<256;j+=32)kout[kh*256+j]=tmpk[j];}}
kernel void sparse_gqa(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device const float*v[[buffer(2)]],device const int*ids[[buffer(3)]],device float*out[[buffer(4)]],constant uint&nsel[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=24)return;uint kvh=h/12;float maxs=-INFINITY;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)maxs=max(maxs,z);}maxs=simd_broadcast_first(maxs);float den=0;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)den+=exp(z-maxs);}den=simd_broadcast_first(den);for(uint j=lane;j<256;j+=32){float acc=0;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint d=0;d<256;d++)z+=q[h*256+d]*k[((uint)id*2+kvh)*256+d];float p=exp(z/16.0f-maxs)/den;acc+=p*v[((uint)id*2+kvh)*256+j];}out[h*256+j]=acc;}}
kernel void gate_apply(device float*x[[buffer(0)]],device const float*g[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<6144)x[i]*=sigm(g[i]);}
kernel void residual_inject(device const float*base[[buffer(0)]],device const float*attn[[buffer(1)]],device const float*inj[[buffer(2)]],device float*out[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<10240){uint g=i/2560,j=i%2560;out[i]=base[i]+attn[j]*inj[g];}}
)METAL";}

typedef struct{float s;uint32_t i;} Pair; static int cmp(const void*a,const void*b){float x=((const Pair*)a)->s,y=((const Pair*)b)->s;return x<y?1:x>y?-1:0;}
static void encmv(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>ps,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:ps];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
int main(int ac,char**av){if(ac!=9){fprintf(stderr,"usage: %s shard8 shard10 hyper hist_idx_raw hist_k hist_v final_ref T\n",av[0]);return 2;}uint32_t T=atoi(av[8]),B=T/4,pos=T-1;float*hyper=rd(av[3],10240*4),*hir=rd(av[7],10240*4),*hist_idx=rd(av[4],(size_t)(T-1)*128*4),*histk=rd(av[5],(size_t)(T-1)*2*256*4),*histv=rd(av[6],(size_t)(T-1)*2*256*4);char er[256];qn_file_map f8,f10;if(qn_file_map_open(&f8,av[1],er,sizeof(er))||qn_file_map_open(&f10,av[2],er,sizeof(er))){fprintf(stderr,"%s\n",er);return 1;}
@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();id<MTLCommandQueue>cq=[d newCommandQueue];NSError*e=nil;id<MTLLibrary>lib=[d newLibraryWithSource:src() options:nil error:&e];if(!lib){fprintf(stderr,"compile %s\n",e.description.UTF8String);return 1;}
#define P(name) id<MTLComputePipelineState> name=[d newComputePipelineStateWithFunction:[lib newFunctionWithName:@#name] error:&e]
P(group_rms4);P(q8_mv);P(q8_rows);P(silu_div4);P(sigmoid_ip);P(mix4);P(bf16_mv4);P(q_last_norm_rope);P(kcomp_rope);P(score_blocks);P(gated_qkv);P(sparse_gqa);P(gate_apply);P(residual_inject);
qn_bf16_metal_view hcn={0},biw={0},iqn={0},ikn={0},qn={0},kn={0};qn_bf16_make_view(d,&f8,485631776,10240,&hcn,er,sizeof(er));qn_bf16_make_view(d,&f8,485549856,40960,&biw,er,sizeof(er));qn_bf16_make_view(d,&f10,487296712,128,&iqn,er,sizeof(er));qn_bf16_make_view(d,&f10,487296456,128,&ikn,er,sizeof(er));qn_bf16_make_view(d,&f10,505401800,256,&qn,er,sizeof(er));qn_bf16_make_view(d,&f10,487296968,256,&kn,er,sizeof(er));
qn_affine_desc hd={485652256,488929056,489031456,320,10240,64,8},hu={489133856,492410656,492513056,10240,320,64,8},idx={485555656,487194056,487245256,640,2560,64,8},qd={505402312,536859592,537842632,12288,2560,64,8},kd={487297480,488608200,488649160,512,2560,64,8},vd={538825672,540136392,540177352,512,2560,64,8},od={488690120,504418760,504910280,2560,6144,64,8};qn_affine_metal_view hvd={0},hvu={0},iv={0},qv={0},kv={0},vv={0},ov={0};qn_affine_make_view(d,&f8,&hd,&hvd,er,sizeof(er));qn_affine_make_view(d,&f8,&hu,&hvu,er,sizeof(er));qn_affine_make_view(d,&f10,&idx,&iv,er,sizeof(er));qn_affine_make_view(d,&f10,&qd,&qv,er,sizeof(er));qn_affine_make_view(d,&f10,&kd,&kv,er,sizeof(er));qn_affine_make_view(d,&f10,&vd,&vv,er,sizeof(er));qn_affine_make_view(d,&f10,&od,&ov,er,sizeof(er));
id<MTLBuffer> hb=[d newBufferWithBytes:hyper length:10240*4 options:MTLResourceStorageModeShared],xnorm=[d newBufferWithLength:10240*4 options:MTLResourceStorageModeShared],lo=[d newBufferWithLength:320*4 options:MTLResourceStorageModeShared],mixw=[d newBufferWithLength:10240*4 options:MTLResourceStorageModeShared],mixed=[d newBufferWithLength:2560*4 options:MTLResourceStorageModeShared],inj=[d newBufferWithLength:4*4 options:MTLResourceStorageModeShared],idxraw=[d newBufferWithLength:640*4 options:MTLResourceStorageModeShared],iq=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],ikblocks=[d newBufferWithLength:(size_t)B*128*4 options:MTLResourceStorageModeShared],scores=[d newBufferWithLength:(size_t)B*4 options:MTLResourceStorageModeShared],histidx=[d newBufferWithBytes:hist_idx length:(size_t)(T-1)*128*4 options:MTLResourceStorageModeShared],qraw=[d newBufferWithLength:12288*4 options:MTLResourceStorageModeShared],kraw=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],vraw=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],q=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],gate=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],kcur=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],vcur=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],allk=[d newBufferWithLength:(size_t)T*2*256*4 options:MTLResourceStorageModeShared],allv=[d newBufferWithLength:(size_t)T*2*256*4 options:MTLResourceStorageModeShared],ids=[d newBufferWithLength:2048*4 options:MTLResourceStorageModeShared],att=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],out=[d newBufferWithLength:2560*4 options:MTLResourceStorageModeShared],final=[d newBufferWithLength:10240*4 options:MTLResourceStorageModeShared];memcpy(allk.contents,histk,(size_t)(T-1)*2*256*4);memcpy(allv.contents,histv,(size_t)(T-1)*2*256*4);
uint32_t n320=320,n10240=10240,O,I;
id<MTLCommandBuffer>cb=[cq commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:group_rms4];[ce setBuffer:hb offset:0 atIndex:0];[ce setBuffer:hcn.buffer offset:0 atIndex:1];[ce setBuffer:xnorm offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];encmv(ce,q8_mv,&hvd,xnorm,lo,320,10240);[ce setComputePipelineState:silu_div4];[ce setBuffer:lo offset:0 atIndex:0];[ce setBytes:&n320 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encmv(ce,q8_mv,&hvu,lo,mixw,10240,320);[ce setComputePipelineState:sigmoid_ip];[ce setBuffer:mixw offset:0 atIndex:0];[ce setBytes:&n10240 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:mix4];[ce setBuffer:xnorm offset:0 atIndex:0];[ce setBuffer:mixw offset:0 atIndex:1];[ce setBuffer:mixed offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:bf16_mv4];[ce setBuffer:biw.buffer offset:0 atIndex:0];[ce setBuffer:xnorm offset:0 atIndex:1];[ce setBuffer:inj offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
encmv(ce,q8_mv,&iv,mixed,idxraw,640,2560);[ce setComputePipelineState:q_last_norm_rope];[ce setBuffer:idxraw offset:0 atIndex:0];[ce setBuffer:iqn.buffer offset:0 atIndex:1];[ce setBuffer:iq offset:0 atIndex:2];[ce setBytes:&pos length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];
// CPU builds complete-block key buffer from historical raw index keys, then GPU norms+RoPE scores.
float*tmp=(float*)malloc((size_t)B*4*128*4);memcpy(tmp,hist_idx,(size_t)B*4*128*4);id<MTLBuffer>blkraw=[d newBufferWithBytes:tmp length:(size_t)B*4*128*4 options:MTLResourceStorageModeShared];free(tmp);cb=[cq commandBuffer];ce=[cb computeCommandEncoder];[ce setComputePipelineState:kcomp_rope];[ce setBuffer:blkraw offset:0 atIndex:0];[ce setBuffer:ikn.buffer offset:0 atIndex:1];[ce setBuffer:ikblocks offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:score_blocks];[ce setBuffer:iq offset:0 atIndex:0];[ce setBuffer:ikblocks offset:0 atIndex:1];[ce setBuffer:scores offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];Pair*p=malloc((size_t)B*sizeof(*p));float*ss=scores.contents;for(uint32_t b=0;b<B;b++)p[b]=(Pair){ss[b],b};qsort(p,B,sizeof(*p),cmp);int*idp=ids.contents;for(uint32_t r=0;r<512;r++)for(uint32_t t=0;t<4;t++)idp[r*4+t]=(int)(p[r].i*4+t);free(p);
cb=[cq commandBuffer];ce=[cb computeCommandEncoder];encmv(ce,q8_mv,&qv,mixed,qraw,12288,2560);encmv(ce,q8_mv,&kv,mixed,kraw,512,2560);encmv(ce,q8_mv,&vv,mixed,vraw,512,2560);[ce setComputePipelineState:gated_qkv];[ce setBuffer:qraw offset:0 atIndex:0];[ce setBuffer:kraw offset:0 atIndex:1];[ce setBuffer:vraw offset:0 atIndex:2];[ce setBuffer:qn.buffer offset:0 atIndex:3];[ce setBuffer:kn.buffer offset:0 atIndex:4];[ce setBuffer:q offset:0 atIndex:5];[ce setBuffer:gate offset:0 atIndex:6];[ce setBuffer:kcur offset:0 atIndex:7];[ce setBuffer:vcur offset:0 atIndex:8];[ce setBytes:&pos length:4 atIndex:9];[ce dispatchThreads:MTLSizeMake(26*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];memcpy((uint8_t*)allk.contents+(size_t)(T-1)*2*256*4,kcur.contents,512*4);memcpy((uint8_t*)allv.contents+(size_t)(T-1)*2*256*4,vcur.contents,512*4);
uint32_t nsel=2048;cb=[cq commandBuffer];ce=[cb computeCommandEncoder];[ce setComputePipelineState:sparse_gqa];[ce setBuffer:q offset:0 atIndex:0];[ce setBuffer:allk offset:0 atIndex:1];[ce setBuffer:allv offset:0 atIndex:2];[ce setBuffer:ids offset:0 atIndex:3];[ce setBuffer:att offset:0 atIndex:4];[ce setBytes:&nsel length:4 atIndex:5];[ce dispatchThreads:MTLSizeMake(24*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gate_apply];[ce setBuffer:att offset:0 atIndex:0];[ce setBuffer:gate offset:0 atIndex:1];[ce dispatchThreads:MTLSizeMake(6144,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encmv(ce,q8_mv,&ov,att,out,2560,6144);[ce setComputePipelineState:residual_inject];[ce setBuffer:hb offset:0 atIndex:0];[ce setBuffer:out offset:0 atIndex:1];[ce setBuffer:inj offset:0 atIndex:2];[ce setBuffer:final offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){fprintf(stderr,"cmd %s\n",cb.error.description.UTF8String);return 1;}estat("half_layer_single_process",final.contents,hir,10240);
}
free(hyper);free(hir);free(hist_idx);free(histk);free(histv);qn_file_map_close(&f8);qn_file_map_close(&f10);return 0;}
