#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import "qn_runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

typedef struct{float s;int i;} Pair;
static int cmp_pair(const void*a,const void*b){float x=((const Pair*)a)->s,y=((const Pair*)b)->s;return x<y?1:x>y?-1:0;}
static void *rd(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f){perror(p);exit(1);}void*x=malloc(n);if(fread(x,1,n,f)!=n){fprintf(stderr,"short %s\n",p);exit(1);}fclose(f);return x;}
static void estat(const char*n,const float*a,const float*b,size_t N){double mx=0,ma=0,se=0,dot=0,aa=0,bb=0;for(size_t i=0;i<N;i++){double e=(double)a[i]-b[i],z=fabs(e);if(z>mx)mx=z;ma+=z;se+=e*e;dot+=(double)a[i]*b[i];aa+=(double)a[i]*a[i];bb+=(double)b[i]*b[i];}printf("%s max=%.6g mae=%.6g rmse=%.6g cos=%.12f\n",n,mx,ma/N,sqrt(se/N),dot/sqrt(aa*bb));}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;
inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}
inline float rinv(uint j){return pow(10000000.0f,-(2.0f*(float)j)/64.0f);}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float s=bf16f(sc[r*G+g]),b=bf16f(bi[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),q*s+b);}}a=simd_sum(a);if(lane==0)y[r]=a;}
kernel void idx_q_norm_rope(device const float*raw[[buffer(0)]],device const ushort*nw[[buffer(1)]],device float*q[[buffer(2)]],constant uint&pos[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=4)return;float ss=0;for(uint j=lane;j<128;j+=32){float z=raw[h*128+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/128.0f+1e-6f);threadgroup float t[128];for(uint j=lane;j<128;j+=32)t[j]=raw[h*128+j]*iv*bf16f(nw[j]);threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=t[j],b=t[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);t[j]=a*c-b*s;t[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)q[h*128+j]=t[j];}
kernel void idx_k_blocks(device const float*rawk[[buffer(0)]],device const ushort*nw[[buffer(1)]],device float*k[[buffer(2)]],constant uint&B[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint b=tid/32;if(b>=B)return;threadgroup float t[128];float ss=0;for(uint j=lane;j<128;j+=32){float z=.25f*(rawk[(b*4)*128+j]+rawk[(b*4+1)*128+j]+rawk[(b*4+2)*128+j]+rawk[(b*4+3)*128+j]);t[j]=z;ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/128.0f+1e-6f);for(uint j=lane;j<128;j+=32)t[j]*=iv*bf16f(nw[j]);threadgroup_barrier(mem_flags::mem_threadgroup);uint pos=b*4;for(uint j=lane;j<32;j+=32){float a=t[j],bb=t[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);t[j]=a*c-bb*s;t[32+j]=bb*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)k[b*128+j]=t[j];}
kernel void idx_score(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device float*sco[[buffer(2)]],constant uint&B[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint b=tid/32;if(b>=B)return;float total=0;for(uint h=0;h<4;h++){float d=0;for(uint j=lane;j<128;j+=32)d+=q[h*128+j]*k[b*128+j];d=simd_sum(d);if(lane==0)total+=max(d,0.0f);}if(lane==0)sco[b]=total*0.08838834764831845f;}
kernel void q_post_rope(device const float*raw[[buffer(0)]],device const ushort*nw[[buffer(1)]],device float*q[[buffer(2)]],device float*g[[buffer(3)]],constant uint&pos[[buffer(4)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=24)return;float ss=0;for(uint j=lane;j<256;j+=32){float z=raw[h*512+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/256.0f+1e-6f);threadgroup float t[256];for(uint j=lane;j<256;j+=32){t[j]=raw[h*512+j]*iv*bf16f(nw[j]);g[h*256+j]=raw[h*512+256+j];}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=t[j],b=t[32+j],ang=(float)pos*rinv(j),c=cos(ang),s=sin(ang);t[j]=a*c-b*s;t[32+j]=b*c+a*s;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<256;j+=32)q[h*256+j]=t[j];}
kernel void sparse_attn(device const float*q[[buffer(0)]],device const float*K[[buffer(1)]],device const float*V[[buffer(2)]],device const int*ids[[buffer(3)]],device float*out[[buffer(4)]],constant uint&N[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=24)return;uint kh=h/12;float m=-INFINITY;for(uint t=0;t<N;t++){uint id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*K[(id*2+kh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)m=max(m,z);}m=simd_broadcast_first(m);float den=0;for(uint t=0;t<N;t++){uint id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*K[(id*2+kh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)den+=exp(z-m);}den=simd_broadcast_first(den);for(uint j=lane;j<256;j+=32){float a=0;for(uint t=0;t<N;t++){uint id=ids[t];float z=0;for(uint d=0;d<256;d++)z+=q[h*256+d]*K[(id*2+kh)*256+d];a+=exp(z/16.0f-m)/den*V[(id*2+kh)*256+j];}out[h*256+j]=a;}}
kernel void gate(device float*x[[buffer(0)]],device const float*g[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<6144)x[i]/=(1.0f+exp(-g[i]));}
)METAL";}
static id<MTLComputePipelineState> ps(id<MTLDevice>d,id<MTLLibrary>l,NSString*n){NSError*e=nil;id<MTLComputePipelineState>p=[d newComputePipelineStateWithFunction:[l newFunctionWithName:n] error:&e];if(!p){fprintf(stderr,"pipeline %s\n",e.description.UTF8String);exit(1);}return p;}
static void qmm(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
int main(int ac,char**av){if(ac!=8){fprintf(stderr,"usage: %s shard x rawk K V ids_ref out_ref\n",av[0]);return 2;}const uint32_t T=2561,B=640,N=2048,pos=T-1;float*x=rd(av[2],2560*4),*rawk=rd(av[3],(size_t)T*128*4),*K=rd(av[4],(size_t)T*2*256*4),*V=rd(av[5],(size_t)T*2*256*4),*oref=rd(av[7],2560*4);int*iref=rd(av[6],N*4);qn_file_map fm;char er[256];if(qn_file_map_open(&fm,av[1],er,sizeof(er))){fprintf(stderr,"%s\n",er);return 1;}@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();id<MTLCommandQueue>cq=[d newCommandQueue];NSError*e=nil;id<MTLLibrary>lib=[d newLibraryWithSource:src() options:nil error:&e];if(!lib){fprintf(stderr,"compile %s\n",e.description.UTF8String);return 1;}id<MTLComputePipelineState>mm=ps(d,lib,@"q8_mv"),iq=ps(d,lib,@"idx_q_norm_rope"),ik=ps(d,lib,@"idx_k_blocks"),is=ps(d,lib,@"idx_score"),qp=ps(d,lib,@"q_post_rope"),att=ps(d,lib,@"sparse_attn"),gp=ps(d,lib,@"gate");
 qn_affine_desc idxd={485555656,487194056,487245256,640,2560,64,8},qd={505402312,536859592,537842632,12288,2560,64,8},od={488690120,504418760,504910280,2560,6144,64,8};qn_affine_metal_view idxv={0},qv={0},ov={0};qn_affine_make_view(d,&fm,&idxd,&idxv,er,sizeof(er));qn_affine_make_view(d,&fm,&qd,&qv,er,sizeof(er));qn_affine_make_view(d,&fm,&od,&ov,er,sizeof(er));qn_bf16_metal_view iqw={0},ikw={0},qnw={0};qn_bf16_make_view(d,&fm,487296712,128,&iqw,er,sizeof(er));qn_bf16_make_view(d,&fm,487296456,128,&ikw,er,sizeof(er));qn_bf16_make_view(d,&fm,505401800,256,&qnw,er,sizeof(er));
 id<MTLBuffer>xb=[d newBufferWithBytes:x length:2560*4 options:MTLResourceStorageModeShared],rkb=[d newBufferWithBytes:rawk length:(size_t)T*128*4 options:MTLResourceStorageModeShared],Kb=[d newBufferWithBytes:K length:(size_t)T*2*256*4 options:MTLResourceStorageModeShared],Vb=[d newBufferWithBytes:V length:(size_t)T*2*256*4 options:MTLResourceStorageModeShared],iraw=[d newBufferWithLength:640*4 options:MTLResourceStorageModeShared],iqb=[d newBufferWithLength:512*4 options:MTLResourceStorageModeShared],ikb=[d newBufferWithLength:(size_t)B*128*4 options:MTLResourceStorageModeShared],sb=[d newBufferWithLength:B*4 options:MTLResourceStorageModeShared],qraw=[d newBufferWithLength:12288*4 options:MTLResourceStorageModeShared],qb=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],gb=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],ib=[d newBufferWithLength:N*4 options:MTLResourceStorageModeShared],ab=[d newBufferWithLength:6144*4 options:MTLResourceStorageModeShared],ob=[d newBufferWithLength:2560*4 options:MTLResourceStorageModeShared];
 // Stage 1 route scores + qraw
 id<MTLCommandBuffer>cb=[cq commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];qmm(ce,mm,&idxv,xb,iraw,640,2560);[ce setComputePipelineState:iq];[ce setBuffer:iraw offset:0 atIndex:0];[ce setBuffer:iqw.buffer offset:0 atIndex:1];[ce setBuffer:iqb offset:0 atIndex:2];[ce setBytes:&pos length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(4*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:ik];[ce setBuffer:rkb offset:0 atIndex:0];[ce setBuffer:ikw.buffer offset:0 atIndex:1];[ce setBuffer:ikb offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:is];[ce setBuffer:iqb offset:0 atIndex:0];[ce setBuffer:ikb offset:0 atIndex:1];[ce setBuffer:sb offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];qmm(ce,mm,&qv,xb,qraw,12288,2560);[ce setComputePipelineState:qp];[ce setBuffer:qraw offset:0 atIndex:0];[ce setBuffer:qnw.buffer offset:0 atIndex:1];[ce setBuffer:qb offset:0 atIndex:2];[ce setBuffer:gb offset:0 atIndex:3];[ce setBytes:&pos length:4 atIndex:4];[ce dispatchThreads:MTLSizeMake(24*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];
 Pair*pairs=malloc(B*sizeof(*pairs));float*scores=(float*)sb.contents;for(int i=0;i<B;i++)pairs[i]=(Pair){scores[i],i};qsort(pairs,B,sizeof(*pairs),cmp_pair);int*ids=(int*)ib.contents;int z=0;for(int j=0;j<512;j++){int b=pairs[j].i;for(int t=0;t<4;t++)ids[z++]=b*4+t;}// integer sort
  for(int i=1;i<(int)N;i++){int v=ids[i],j=i-1;while(j>=0&&ids[j]>v){ids[j+1]=ids[j];j--;}ids[j+1]=v;}
 uint32_t mism=0;for(uint32_t i=0;i<N;i++)if(ids[i]!=iref[i])mism++;printf("route_ids mismatch=%u/%u\n",mism,N);
 // Stage 2 attention+gate+O
 cb=[cq commandBuffer];ce=[cb computeCommandEncoder];[ce setComputePipelineState:att];[ce setBuffer:qb offset:0 atIndex:0];[ce setBuffer:Kb offset:0 atIndex:1];[ce setBuffer:Vb offset:0 atIndex:2];[ce setBuffer:ib offset:0 atIndex:3];[ce setBuffer:ab offset:0 atIndex:4];[ce setBytes:&N length:4 atIndex:5];[ce dispatchThreads:MTLSizeMake(24*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gp];[ce setBuffer:ab offset:0 atIndex:0];[ce setBuffer:gb offset:0 atIndex:1];[ce dispatchThreads:MTLSizeMake(6144,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];qmm(ce,mm,&ov,ab,ob,2560,6144);[ce endEncoding];[cb commit];[cb waitUntilCompleted];estat("decode_e2e",ob.contents,oref,2560);free(pairs);
 }free(x);free(rawk);free(K);free(V);free(oref);free(iref);qn_file_map_close(&fm);return 0;}
