#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import "qn_runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
static void*rd(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f){perror("fopen");exit(1);}void*x=malloc(n);if(fread(x,1,n,f)!=n){fprintf(stderr,"short %s\n",p);exit(1);}fclose(f);return x;}
static void es(const char*n,const float*a,const float*b,size_t N){double mx=0,ma=0,se=0;for(size_t i=0;i<N;i++){double e=(double)a[i]-b[i],z=fabs(e);if(z>mx)mx=z;ma+=z;se+=e*e;}printf("%s max=%.6g mae=%.6g rmse=%.6g\n",n,mx,ma/N,sqrt(se/N));}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal; inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}
kernel void q4_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&outdim[[buffer(5)]],constant uint&indim[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint row=tid/32;if(row>=outdim)return;uint groups=indim/64,wcols=indim/8;float a=0;device const uint*wr=w+row*wcols;device const ushort*sr=sc+row*groups;device const ushort*br=bi+row*groups;for(uint g=0;g<groups;g++){float s=bf16f(sr[g]),b=bf16f(br[g]);uint xb=g*64,wb=g*8;for(uint j=lane;j<8;j+=32){uint p=wr[wb+j],k=xb+j*8;for(uint t=0;t<8;t++)a+=x[k+t]*(float)((p>>(4*t))&15u)*s + x[k+t]*b;}}a=simd_sum(a);if(lane==0)y[row]=a;}
kernel void silu_mul(device const float*g[[buffer(0)]],device const float*u[[buffer(1)]],device float*h[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<640){float z=g[i];h[i]=(z/(1.0f+exp(-z)))*u[i];}}
)METAL";}
static void enc(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>ps,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:ps];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
int main(int ac,char**av){if(ac!=8){fprintf(stderr,"usage: %s shard9 shard10 x gref uref href dref\n",av[0]);return 2;}float*x=rd(av[3],2560*4),*gr=rd(av[4],640*4),*ur=rd(av[5],640*4),*hr=rd(av[6],640*4),*dr=rd(av[7],2560*4);char er[256];qn_file_map f9,f10;qn_file_map_open(&f9,av[1],er,sizeof(er));qn_file_map_open(&f10,av[2],er,sizeof(er));@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();NSError*e=nil;id<MTLLibrary>lib=[d newLibraryWithSource:src() options:nil error:&e];id<MTLComputePipelineState>mm=[d newComputePipelineStateWithFunction:[lib newFunctionWithName:@"q4_mv"] error:&e],sm=[d newComputePipelineStateWithFunction:[lib newFunctionWithName:@"silu_mul"] error:&e];id<MTLCommandQueue>cq=[d newCommandQueue];uint64_t E=103;uint64_t gw=E*(uint64_t)640*320*4,gs=E*(uint64_t)640*40*2,dw=E*(uint64_t)2560*80*4,ds=E*(uint64_t)2560*10*2;qn_affine_desc gd={896+gw,419431296+gs,445645696+gs,640,2560,64,4},ud={471860096+gw,891290496+gs,917504896+gs,640,2560,64,4},dd={10696+dw,419441096+ds,445655496+ds,2560,640,64,4};qn_affine_metal_view gv={0},uv={0},dv={0};if(qn_affine_make_view(d,&f9,&gd,&gv,er,sizeof(er))||qn_affine_make_view(d,&f9,&ud,&uv,er,sizeof(er))||qn_affine_make_view(d,&f10,&dd,&dv,er,sizeof(er))){fprintf(stderr,"view %s\n",er);return 1;}id<MTLBuffer>xb=[d newBufferWithBytes:x length:2560*4 options:MTLResourceStorageModeShared],gb=[d newBufferWithLength:640*4 options:MTLResourceStorageModeShared],ub=[d newBufferWithLength:640*4 options:MTLResourceStorageModeShared],hb=[d newBufferWithLength:640*4 options:MTLResourceStorageModeShared],db=[d newBufferWithLength:2560*4 options:MTLResourceStorageModeShared];id<MTLCommandBuffer>cb=[cq commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];enc(ce,mm,&gv,xb,gb,640,2560);enc(ce,mm,&uv,xb,ub,640,2560);[ce setComputePipelineState:sm];[ce setBuffer:gb offset:0 atIndex:0];[ce setBuffer:ub offset:0 atIndex:1];[ce setBuffer:hb offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(640,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];enc(ce,mm,&dv,hb,db,2560,640);[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){fprintf(stderr,"cmd %s\n",cb.error.description.UTF8String);return 1;}es("gate",gb.contents,gr,640);es("up",ub.contents,ur,640);es("hidden",hb.contents,hr,640);es("down",db.contents,dr,2560);}
free(x);free(gr);free(ur);free(hr);free(dr);qn_file_map_close(&f9);qn_file_map_close(&f10);return 0;}
