#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import "../qn_runtime.h"
#include <mach/mach_time.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

typedef struct { const char*name; qn_affine_desc d; } C;
static void*readall(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f){perror(p);exit(1);}void*x=malloc(n);if(fread(x,1,n,f)!=n){fprintf(stderr,"short %s\n",p);exit(1);}fclose(f);return x;}
static double ms(void){static mach_timebase_info_data_t t;if(!t.denom)mach_timebase_info(&t);return(double)mach_absolute_time()*t.numer/t.denom/1e6;}
int main(int argc,char**argv){if(argc!=5){fprintf(stderr,"usage: %s shard x refs iters\n",argv[0]);return 2;}int iters=atoi(argv[4]);C c[3]={{"q",{505402312,536859592,537842632,12288,2560,64,8}},{"k",{487297480,488608200,488649160,512,2560,64,8}},{"v",{538825672,540136392,540177352,512,2560,64,8}}};char er[256];qn_file_map m;if(qn_file_map_open(&m,argv[1],er,sizeof(er))){fprintf(stderr,"map %s\n",er);return 1;}float*x=readall(argv[2],2560*4);
@autoreleasepool{id<MTLDevice>d=MTLCreateSystemDefaultDevice();id<MTLCommandQueue>q=[d newCommandQueue];NSError*e=nil;NSString*s=@"#include <metal_stdlib>\nusing namespace metal;inline float bf(ushort v){return as_type<float>((uint)v<<16);}struct P{uint outd;uint ind;uint groups;uint wcols;};kernel void q8mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant P&p[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid>>5;if(r>=p.outd)return;device const uint*wr=w+r*p.wcols;device const ushort*sr=sc+r*p.groups;device const ushort*br=bi+r*p.groups;float a=0;for(uint wi=lane;wi<p.wcols;wi+=32){uint g=wi>>4;uint u=wr[wi],k=wi*4;float z=bf(sr[g]),b=bf(br[g]);float4 v=float4(u&255u,(u>>8)&255u,(u>>16)&255u,(u>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),v*z+b);}a=simd_sum(a);if(lane==0)y[r]=a;}";id<MTLLibrary>l=[d newLibraryWithSource:s options:nil error:&e];id<MTLComputePipelineState>ps=[d newComputePipelineStateWithFunction:[l newFunctionWithName:@"q8mv"] error:&e];id<MTLBuffer>xb=[d newBufferWithBytes:x length:2560*4 options:MTLResourceStorageModeShared];qn_affine_metal_view vw[3];id<MTLBuffer>yb[3];struct P{uint32_t outd,ind,groups,wcols;}p[3];for(int i=0;i<3;i++){if(qn_affine_make_view(d,&m,&c[i].d,&vw[i],er,sizeof(er))){fprintf(stderr,"view %s %s\n",c[i].name,er);return 1;}yb[i]=[d newBufferWithLength:c[i].d.out_dim*4 options:MTLResourceStorageModeShared];p[i]=(struct P){c[i].d.out_dim,c[i].d.in_dim,c[i].d.in_dim/64,c[i].d.in_dim/4};}
for(int w=0;w<5;w++){id<MTLCommandBuffer>cb=[q commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:ps];for(int i=0;i<3;i++){[ce setBuffer:vw[i].weight offset:0 atIndex:0];[ce setBuffer:vw[i].scales offset:0 atIndex:1];[ce setBuffer:vw[i].biases offset:0 atIndex:2];[ce setBuffer:xb offset:0 atIndex:3];[ce setBuffer:yb[i] offset:0 atIndex:4];[ce setBytes:&p[i] length:sizeof(p[i]) atIndex:5];[ce dispatchThreads:MTLSizeMake((NSUInteger)c[i].d.out_dim*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}[ce endEncoding];[cb commit];[cb waitUntilCompleted];}
double t0=ms();for(int z=0;z<iters;z++){id<MTLCommandBuffer>cb=[q commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:ps];for(int i=0;i<3;i++){[ce setBuffer:vw[i].weight offset:0 atIndex:0];[ce setBuffer:vw[i].scales offset:0 atIndex:1];[ce setBuffer:vw[i].biases offset:0 atIndex:2];[ce setBuffer:xb offset:0 atIndex:3];[ce setBuffer:yb[i] offset:0 atIndex:4];[ce setBytes:&p[i] length:sizeof(p[i]) atIndex:5];[ce dispatchThreads:MTLSizeMake((NSUInteger)c[i].d.out_dim*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}[ce endEncoding];[cb commit];[cb waitUntilCompleted];}printf("native_qkv_batch avg_ms=%.4f\n",(ms()-t0)/iters);
for(int i=0;i<3;i++){char rp[1024];snprintf(rp,sizeof(rp),"%s/%s.bin",argv[3],c[i].name);float*r=readall(rp,c[i].d.out_dim*4),*y=(float*)yb[i].contents;double ma=0,se=0;for(uint32_t j=0;j<c[i].d.out_dim;j++){double x=(double)y[j]-r[j];if(fabs(x)>ma)ma=fabs(x);se+=x*x;}printf("%s max=%.3g rmse=%.3g\n",c[i].name,ma,sqrt(se/c[i].d.out_dim));free(r);}}
free(x);qn_file_map_close(&m);return 0;}
