#import <Foundation/Foundation.h>
#include "../qn_ple_layer.h"
#include <mach/mach_time.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
static double ms(){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return(double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static int run(uint32_t T){const char*D=getenv("QWEN4_TEST_MODEL"),*M=getenv("QWEN4_TEST_MANIFEST");if(!D||!M)return 77;char ng[1200];snprintf(ng,sizeof(ng),"%s/ngram_table.bin",D);size_t N=(size_t)T*10240;float*in=malloc(N*4),*seq=malloc(N*4),*bat=malloc(N*4),*cs1=calloc((size_t)10240*9,4),*cs2=calloc((size_t)10240*9,4);int64_t*ids=malloc((size_t)T*8);for(size_t i=0;i<N;i++)in[i]=sinf((float)i*.0011f)*.04f+cosf((float)i*.00027f)*.02f;for(uint32_t t=0;t<T;t++)ids[t]=(int64_t)(760+(t*7919u)%200000u);char e[512]={0};qn_ple_layer*a=0,*b=0;qn_ple_config c={D,M,ng};if(qn_ple_layer_open(&a,&c,e,sizeof(e))||qn_ple_layer_open(&b,&c,e,sizeof(e))){fprintf(stderr,"open %s\n",e);return 1;}int64_t hseq[2]={248044,248044},hbat[2]={248044,248044};double t0=ms();for(uint32_t t=0;t<T;t++){qn_ple_input pi={0};pi.hyper_state=in+(size_t)t*10240;pi.token_history[0]=hseq[0];pi.token_history[1]=hseq[1];pi.token_history[2]=ids[t];pi.conv_state=cs1;qn_ple_output po={0};po.ple_output=seq+(size_t)t*10240;if(qn_ple_layer_forward(a,&pi,&po,e,sizeof(e))){fprintf(stderr,"seq %s\n",e);return 2;}hseq[0]=hseq[1];hseq[1]=ids[t];}double st=ms()-t0;t0=ms();if(qn_ple_layer_forward_batch(b,in,ids,T,hbat,cs2,bat,e,sizeof(e))){fprintf(stderr,"batch %s\n",e);return 3;}double bt=ms()-t0;double mx=0,se=0,smx=0,sse=0;for(size_t i=0;i<N;i++){double z=(double)seq[i]-bat[i];mx=fmax(mx,fabs(z));se+=z*z;}for(size_t i=0;i<(size_t)10240*9;i++){double z=(double)cs1[i]-cs2[i];smx=fmax(smx,fabs(z));sse+=z*z;}printf("T=%u seq=%.3fms batch=%.3fms speedup=%.3fx out_max=%.3g out_rmse=%.3g state_max=%.3g state_rmse=%.3g hist=%lld,%lld/%lld,%lld\n",T,st,bt,st/bt,mx,sqrt(se/N),smx,sqrt(sse/(10240.0*9.0)),(long long)hseq[0],(long long)hseq[1],(long long)hbat[0],(long long)hbat[1]);qn_ple_layer_close(a);qn_ple_layer_close(b);free(in);free(seq);free(bat);free(cs1);free(cs2);free(ids);return (mx>1e-4||smx>1e-4||hseq[0]!=hbat[0]||hseq[1]!=hbat[1])?4:0;}
int main(){@autoreleasepool{int r=run(5);if(r)return r;return run(16);}}
