#import <Foundation/Foundation.h>
#include "qn_qwen4_layer.h"
#include <mach/mach_time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static double ms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return(double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static double statv(const char*n,const float*a,const float*b,size_t N){double mx=0,se=0,dot=0,aa=0,bb=0;for(size_t i=0;i<N;i++){double x=a[i],y=b[i],d=x-y;mx=fmax(mx,fabs(d));se+=d*d;dot+=x*y;aa+=x*x;bb+=y*y;}printf("%s max=%.9g rmse=%.9g cos=%.12f\n",n,mx,sqrt(se/N),dot/sqrt(aa*bb));return mx;}
static int run(uint32_t base,uint32_t T){const char*D=getenv("QWEN4_TEST_MODEL"),*M=getenv("QWEN4_TEST_MANIFEST");if(!D||!M)return 77;size_t H=(size_t)T*10240,IC=(size_t)(base+T)*128,KC=(size_t)(base+T)*512;float*in=malloc(H*4),*seq=malloc(H*4),*bat=malloc(H*4),*si=malloc(IC*4),*bi=malloc(IC*4),*sk=malloc(KC*4),*bk=malloc(KC*4),*sv=malloc(KC*4),*bv=malloc(KC*4);if(!in||!seq||!bat||!si||!bi||!sk||!bk||!sv||!bv)return 70;for(size_t i=0;i<H;i++)in[i]=sinf((float)i*.00117f)*.025f+cosf((float)i*.00029f)*.009f;for(size_t i=0;i<(size_t)base*128;i++)si[i]=sinf((float)i*.00231f)*.021f+cosf((float)i*.00017f)*.007f;for(size_t i=0;i<(size_t)base*512;i++){sk[i]=sinf((float)i*.00191f)*.019f+cosf((float)i*.00013f)*.006f;sv[i]=sinf((float)i*.00141f)*.023f-cosf((float)i*.00011f)*.005f;}memcpy(bi,si,(size_t)base*128*4);memcpy(bk,sk,(size_t)base*512*4);memcpy(bv,sv,(size_t)base*512*4);char e[1024]={0};qn_qwen4_layer*a=0,*b=0;qn_qwen4_layer_config c={0};c.layer_index=3;c.model_dir=D;c.manifest_path=M;if(qn_qwen4_layer_open(&a,&c,e,sizeof e)||qn_qwen4_layer_open(&b,&c,e,sizeof e)){fprintf(stderr,"open: %s\n",e);return 1;}double t0=ms();for(uint32_t t=0;t<T;t++){uint32_t p=base+t;float ci[128],ck[512],cv[512];qn_qwen4_decode_input di={in+(size_t)t*10240,si,sk,sv,p};qn_qwen4_decode_output o={0};o.hyper_state=seq+(size_t)t*10240;o.indexer_raw_key=ci;o.key_cache=ck;o.value_cache=cv;if(qn_qwen4_layer_forward_decode(a,&di,&o,e,sizeof e)){fprintf(stderr,"seq %u: %s\n",t,e);return 2;}memcpy(si+(size_t)p*128,ci,128*4);memcpy(sk+(size_t)p*512,ck,512*4);memcpy(sv+(size_t)p*512,cv,512*4);}double st=ms()-t0,bt=0;if(qn_qwen4_layer_forward_prefill_batch(b,in,base,T,bi,bk,bv,bat,&bt,e,sizeof e)){fprintf(stderr,"batch: %s\n",e);return 3;}printf("base=%u T=%u seq=%.3fms batch=%.3fms\n",base,T,st,bt);double m0=statv("output",seq,bat,H),m1=statv("index",si+(size_t)base*128,bi+(size_t)base*128,(size_t)T*128),m2=statv("key",sk+(size_t)base*512,bk+(size_t)base*512,(size_t)T*512),m3=statv("value",sv+(size_t)base*512,bv+(size_t)base*512,(size_t)T*512);qn_qwen4_layer_close(a);qn_qwen4_layer_close(b);free(in);free(seq);free(bat);free(si);free(bi);free(sk);free(bk);free(sv);free(bv);return (m0>1e-5||m1>1e-5||m2>1e-5||m3>1e-5)?4:0;}
int main(){@autoreleasepool{int a=run(1024,64);if(a)return a;a=run(1984,64);if(a)return a;a=run(2048,64);if(a)return a;a=run(4096,64);if(a)return a;a=run(8128,64);if(a)return a;return run(16320,64)||run(32704,64)||run(65472,64);}}
