#import <Foundation/Foundation.h>
#include "qn_qwen4_layer.h"
#include <mach/mach_time.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
static double ms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return(double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static void statv(const char*n,const float*a,const float*b,size_t N){double mx=0,se=0,dot=0,aa=0,bb=0;for(size_t i=0;i<N;i++){double d=(double)a[i]-b[i];mx=fmax(mx,fabs(d));se+=d*d;dot+=(double)a[i]*b[i];aa+=(double)a[i]*a[i];bb+=(double)b[i]*b[i];}printf("%s max=%.3g rmse=%.3g cos=%.12f\n",n,mx,sqrt(se/N),dot/sqrt(aa*bb));}
static int run(uint32_t T){const char*D=getenv("QWEN4_TEST_MODEL"),*M=getenv("QWEN4_TEST_MANIFEST");if(!D||!M)return 77;size_t H=(size_t)T*10240,I=(size_t)T*128,K=(size_t)T*512;float*in=malloc(H*4),*seq=malloc(H*4),*bat=malloc(H*4),*si=calloc(I,4),*sk=calloc(K,4),*sv=calloc(K,4),*bi=calloc(I,4),*bk=calloc(K,4),*bv=calloc(K,4);for(size_t i=0;i<H;i++)in[i]=sinf((float)i*.00117f)*.025f+cosf((float)i*.00029f)*.009f;char e[1024]={0};qn_qwen4_layer *a=0,*b=0;qn_qwen4_layer_config c={0};c.layer_index=3;c.model_dir=D;c.manifest_path=M;if(qn_qwen4_layer_open(&a,&c,e,sizeof(e))||qn_qwen4_layer_open(&b,&c,e,sizeof(e))){fprintf(stderr,"open %s\n",e);return 1;}double t0=ms();for(uint32_t t=0;t<T;t++){float ci[128],ck[512],cv[512];qn_qwen4_decode_input di={in+(size_t)t*10240,si,sk,sv,t};qn_qwen4_decode_output o={0};o.hyper_state=seq+(size_t)t*10240;o.indexer_raw_key=ci;o.key_cache=ck;o.value_cache=cv;if(qn_qwen4_layer_forward_decode(a,&di,&o,e,sizeof(e))){fprintf(stderr,"seq %u %s\n",t,e);return 2;}memcpy(si+(size_t)t*128,ci,128*4);memcpy(sk+(size_t)t*512,ck,512*4);memcpy(sv+(size_t)t*512,cv,512*4);}double st=ms()-t0,bt=0;if(qn_qwen4_layer_forward_prefill_batch(b,in,0,T,bi,bk,bv,bat,&bt,e,sizeof(e))){fprintf(stderr,"batch %s\n",e);return 3;}printf("T=%u seq=%.3fms batch=%.3fms speedup=%.3fx\n",T,st,bt,st/bt);statv("output",seq,bat,H);statv("index",si,bi,I);statv("key",sk,bk,K);statv("value",sv,bv,K);double mx=0;for(size_t i=0;i<H;i++)mx=fmax(mx,fabs((double)seq[i]-bat[i]));qn_qwen4_layer_close(a);qn_qwen4_layer_close(b);free(in);free(seq);free(bat);free(si);free(sk);free(sv);free(bi);free(bk);free(bv);return mx>1e-4?4:0;}
int main(){@autoreleasepool{int r=run(5);if(r)return r;return run(16);}}
