#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "qn_mtp_head.h"
#include "qn_qwen4_layer.h"
#include "qn_manifest.h"
#include "qn_runtime.h"
#include <mach/mach_time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define QN_MTP_CAP 8192u

struct qn_mtp_head {
    char model_dir[1024];
    qn_manifest *manifest;
    qn_file_map maps[12]; char shard_names[12][96]; uint32_t map_count;
    qn_model_io *io;
    qn_qwen4_layer *layer;
    __strong id<MTLDevice> dev; __strong id<MTLCommandQueue> queue; __strong id<MTLLibrary> lib; __strong NSMutableDictionary *pipes;
    qn_bf16_metal_view pre_emb_norm, pre_hid_norm, mix_norm;
    qn_affine_metal_view fc_emb, fc_hid, mix_down, mix_up;
    __strong id<MTLBuffer> emb,en,ep,hprev,hn,hp,layer_in,mix_xn,mix_lo,mix_w,mixed;
    float *index_hist,*key_hist,*value_hist;
    uint32_t seq_offset, pos_base;
};

static void E(char*e,size_t n,const char*s){if(e&&n)snprintf(e,n,"%s",s?s:"mtp head error");}
static double msnow(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return (double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;
inline float bf16f(ushort v){return as_type<float>((uint)v<<16);} inline float sigm(float x){return 1.0f/(1.0f+exp(-x));}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);uint j=lane>>1,t=(lane&1u)*2u,p=w[r*W+g*16+j],k=g*64+j*4+t;float2 q=float2((p>>(8*t))&255u,(p>>(8*(t+1)))&255u);a+=dot(float2(x[k],x[k+1]),q*sc+bi);}a=simd_sum(a);if(lane==0)y[r]=a;}
kernel void q8_rows4(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint z=tid/32,row=z/O,r=z-row*O;if(row>=4)return;device const float*xr=x+row*I;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);uint j=lane>>1,t=(lane&1u)*2u,p=w[r*W+g*16+j],k=g*64+j*4+t;float2 q=float2((p>>(8*t))&255u,(p>>(8*(t+1)))&255u);a+=dot(float2(xr[k],xr[k+1]),q*sc+bi);}a=simd_sum(a);if(lane==0)y[row*O+r]=a;}
kernel void rms_weighted(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],constant uint&N[[buffer(3)]],uint lane[[thread_index_in_simdgroup]]){float ss=0;for(uint j=lane;j<N;j+=32){float v=x[j];ss+=v*v;}ss=simd_sum(ss);float iv=rsqrt(ss/(float)N+1e-6f);for(uint j=lane;j<N;j+=32)y[j]=x[j]*iv*bf16f(w[j]);}
kernel void add_ep4(device const float*h[[buffer(0)]],device const float*e[[buffer(1)]],device float*y[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<10240)y[i]=h[i]+e[i%2560];}
kernel void group_rms4(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j++)if((j&31u)==lane)y[g*2560+j]=x[g*2560+j]*iv*bf16f(w[g*2560+j]);}
kernel void silu_div4(device float*x[[buffer(0)]],uint i[[thread_position_in_grid]]){if(i<320){float z=x[i]*0.25f;x[i]=z*sigm(z);}}
kernel void sigmoid_ip(device float*x[[buffer(0)]],uint i[[thread_position_in_grid]]){if(i<10240)x[i]=sigm(x[i]);}
kernel void mix4(device const float*x[[buffer(0)]],device const float*w[[buffer(1)]],device float*y[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<2560){float a=0;for(uint g=0;g<4;g++)a+=x[g*2560+i]*w[g*2560+i];y[i]=a*0.25f;}}
)METAL";}
static id<MTLComputePipelineState>P(qn_mtp_head*h,NSString*n,NSError**e){id p=h->pipes[n];if(p)return p;id f=[h->lib newFunctionWithName:n];if(!f)return nil;p=[h->dev newComputePipelineStateWithFunction:f error:e];if(p)h->pipes[n]=p;return p;}
static qn_file_map*MF(qn_mtp_head*h,const char*sh,char*e,size_t n){for(uint32_t i=0;i<h->map_count;i++)if(!strcmp(h->shard_names[i],sh))return &h->maps[i];if(h->map_count>=12){E(e,n,"too many MTP outer shards");return NULL;}uint32_t i=h->map_count;char path[1200];snprintf(path,sizeof(path),"%s/%s",h->model_dir,sh);h->maps[i].fd=-1;if(qn_file_map_open(&h->maps[i],path,e,n))return NULL;snprintf(h->shard_names[i],sizeof(h->shard_names[i]),"%s",sh);h->map_count++;return &h->maps[i];}
static int TM(qn_mtp_head*h,const char*name,qn_tensor_meta*t,char*e,size_t n){return qn_manifest_tensor(h->manifest,name,t,e,n);}
static int BF(qn_mtp_head*h,const char*name,uint64_t N,qn_bf16_metal_view*v,char*e,size_t n){qn_tensor_meta t;if(TM(h,name,&t,e,n))return -1;qn_file_map*m=MF(h,t.shard,e,n);return m?qn_bf16_make_view(h->dev,m,t.file_offset,N,v,e,n):-1;}
static int AF(qn_mtp_head*h,const char*base,uint32_t O,uint32_t I,qn_affine_metal_view*v,char*e,size_t n){char k[256];qn_tensor_meta w,s,b;snprintf(k,sizeof(k),"%s.weight",base);if(TM(h,k,&w,e,n))return -1;snprintf(k,sizeof(k),"%s.scales",base);if(TM(h,k,&s,e,n))return -1;snprintf(k,sizeof(k),"%s.biases",base);if(TM(h,k,&b,e,n))return -1;if(strcmp(w.shard,s.shard)||strcmp(w.shard,b.shard)){E(e,n,"MTP affine split across shards");return -1;}qn_file_map*m=MF(h,w.shard,e,n);qn_affine_desc d={w.file_offset,s.file_offset,b.file_offset,O,I,64,8};return m?qn_affine_make_view(h->dev,m,&d,v,e,n):-1;}
static void ENC(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
static void ENC4(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)4*O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}

int qn_mtp_head_open(qn_mtp_head**out,const qn_mtp_head_config*c,char*e,size_t n){if(!out||!c||!c->model_dir||!c->manifest_path||!c->io){E(e,n,"invalid MTP config");return -1;}qn_mtp_head*h=calloc(1,sizeof(*h));if(!h){E(e,n,"MTP allocation failed");return -1;}snprintf(h->model_dir,sizeof(h->model_dir),"%s",c->model_dir);h->io=c->io;for(int i=0;i<12;i++)h->maps[i].fd=-1;h->pos_base=UINT32_MAX;if(qn_manifest_open(&h->manifest,c->manifest_path,e,n)){free(h);return -1;}@autoreleasepool{h->dev=MTLCreateSystemDefaultDevice();h->queue=[h->dev newCommandQueue];NSError*x=nil;h->lib=[h->dev newLibraryWithSource:src() options:nil error:&x];if(!h->lib){E(e,n,x.description.UTF8String);qn_mtp_head_close(h);return -1;}h->pipes=[NSMutableDictionary dictionary];for(NSString*k in @[@"q8_mv",@"q8_rows4",@"rms_weighted",@"add_ep4",@"group_rms4",@"silu_div4",@"sigmoid_ip",@"mix4"])if(!P(h,k,&x)){E(e,n,x.description.UTF8String);qn_mtp_head_close(h);return -1;}
 if(BF(h,"language_model.mtp.pre_fc_norm_embedding.weight",2560,&h->pre_emb_norm,e,n)||BF(h,"language_model.mtp.pre_fc_norm_hidden.weight",10240,&h->pre_hid_norm,e,n)||BF(h,"language_model.mtp.hyper_connection_mixer.hc_norm.weight",10240,&h->mix_norm,e,n)||AF(h,"language_model.mtp.fc_embedding",2560,2560,&h->fc_emb,e,n)||AF(h,"language_model.mtp.fc_hidden",2560,2560,&h->fc_hid,e,n)||AF(h,"language_model.mtp.hyper_connection_mixer.input_mix_weight_down",320,10240,&h->mix_down,e,n)||AF(h,"language_model.mtp.hyper_connection_mixer.input_mix_weight_up",10240,320,&h->mix_up,e,n)){qn_mtp_head_close(h);return -1;}
 qn_qwen4_layer_config lc={0};lc.layer_index=0;lc.model_dir=c->model_dir;lc.manifest_path=c->manifest_path;lc.tensor_prefix="language_model.mtp.layers.0";if(qn_qwen4_layer_open(&h->layer,&lc,e,n)){qn_mtp_head_close(h);return -1;}
#define B(name,bytes) h->name=[h->dev newBufferWithLength:(bytes) options:MTLResourceStorageModeShared];if(!h->name){E(e,n,"MTP Metal buffer allocation failed");qn_mtp_head_close(h);return -1;}
 B(emb,2560*4);B(en,2560*4);B(ep,2560*4);B(hprev,10240*4);B(hn,10240*4);B(hp,10240*4);B(layer_in,10240*4);B(mix_xn,10240*4);B(mix_lo,320*4);B(mix_w,10240*4);B(mixed,2560*4);
#undef B
 h->index_hist=calloc((size_t)QN_MTP_CAP*128,sizeof(float));h->key_hist=calloc((size_t)QN_MTP_CAP*512,sizeof(float));h->value_hist=calloc((size_t)QN_MTP_CAP*512,sizeof(float));if(!h->index_hist||!h->key_hist||!h->value_hist){E(e,n,"MTP cache allocation failed");qn_mtp_head_close(h);return -1;}
 }*out=h;return 0;}

int qn_mtp_head_reset(qn_mtp_head*h){if(!h)return -1;h->seq_offset=0;h->pos_base=UINT32_MAX;if(h->layer)qn_qwen4_layer_invalidate_resident_cache(h->layer);return 0;}
uint32_t qn_mtp_head_seq_offset(qn_mtp_head*h){return h?h->seq_offset:0;}

int qn_mtp_head_truncate(qn_mtp_head*h,uint32_t off){if(!h||off>h->seq_offset)return -1;h->seq_offset=off;if(h->layer)qn_qwen4_layer_invalidate_resident_cache(h->layer);return 0;}

int qn_mtp_head_append_history(qn_mtp_head*h,const float*stream_prev,uint32_t token_id,uint32_t abs_position,double*elapsed,char*e,size_t n){
 if(!h||!stream_prev){E(e,n,"invalid MTP history args");return -1;}if(h->seq_offset>=QN_MTP_CAP){E(e,n,"MTP cache full");return -1;}if(h->pos_base==UINT32_MAX)h->pos_base=abs_position;if(abs_position!=h->pos_base+h->seq_offset){E(e,n,"MTP history position gap");return -1;}double t0=msnow();float ev[2560];if(qn_model_io_embed(h->io,token_id,ev,e,n))return -1;memcpy(h->emb.contents,ev,2560*4);memcpy(h->hprev.contents,stream_prev,10240*4);
 @autoreleasepool{NSError*x=nil;id q8=P(h,@"q8_mv",&x),q84=P(h,@"q8_rows4",&x),rms=P(h,@"rms_weighted",&x),add=P(h,@"add_ep4",&x);if(!q8||!q84||!rms||!add){E(e,n,x.description.UTF8String);return -1;}id<MTLCommandBuffer>cb=[h->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];uint32_t N=2560;[ce setComputePipelineState:rms];[ce setBuffer:h->emb offset:0 atIndex:0];[ce setBuffer:h->pre_emb_norm.buffer offset:0 atIndex:1];[ce setBuffer:h->en offset:0 atIndex:2];[ce setBytes:&N length:4 atIndex:3];[ce dispatchThreadgroups:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC(ce,q8,&h->fc_emb,h->en,h->ep,2560,2560);N=10240;[ce setComputePipelineState:rms];[ce setBuffer:h->hprev offset:0 atIndex:0];[ce setBuffer:h->pre_hid_norm.buffer offset:0 atIndex:1];[ce setBuffer:h->hn offset:0 atIndex:2];[ce setBytes:&N length:4 atIndex:3];[ce dispatchThreadgroups:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC4(ce,q84,&h->fc_hid,h->hn,h->hp,2560,2560);[ce setComputePipelineState:add];[ce setBuffer:h->hp offset:0 atIndex:0];[ce setBuffer:h->ep offset:0 atIndex:1];[ce setBuffer:h->layer_in offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}}
 float layer_out[10240],idx[128],k[512],v[512];qn_qwen4_decode_input in={0};in.hyper_state=h->layer_in.contents;in.indexer_raw_history=h->index_hist;in.key_history=h->key_hist;in.value_history=h->value_hist;in.position=h->seq_offset;in.position_base=h->pos_base;qn_qwen4_decode_output lo={0};lo.hyper_state=layer_out;lo.indexer_raw_key=idx;lo.key_cache=k;lo.value_cache=v;if(qn_qwen4_layer_forward_decode(h->layer,&in,&lo,e,n))return -1;memcpy(h->index_hist+(size_t)h->seq_offset*128,idx,128*4);memcpy(h->key_hist+(size_t)h->seq_offset*512,k,512*4);memcpy(h->value_hist+(size_t)h->seq_offset*512,v,512*4);h->seq_offset++;if(elapsed)*elapsed=msnow()-t0;return 0;
}

int qn_mtp_head_forward(qn_mtp_head*h,const float*stream_prev,uint32_t token_id,uint32_t abs_position,float*stream_out,qn_mtp_head_output*out,char*e,size_t n){if(!h||!stream_prev||!stream_out||!out){E(e,n,"invalid MTP forward args");return -1;}if(h->seq_offset>=QN_MTP_CAP){E(e,n,"MTP cache full");return -1;}if(h->pos_base==UINT32_MAX)h->pos_base=abs_position;if(abs_position!=h->pos_base+h->seq_offset){E(e,n,"MTP absolute position gap");return -1;}memset(out,0,sizeof(*out));double t0=msnow();float ev[2560];if(qn_model_io_embed(h->io,token_id,ev,e,n))return -1;memcpy(h->emb.contents,ev,2560*4);memcpy(h->hprev.contents,stream_prev,10240*4);
 @autoreleasepool{NSError*x=nil;id q8=P(h,@"q8_mv",&x),q84=P(h,@"q8_rows4",&x),rms=P(h,@"rms_weighted",&x),add=P(h,@"add_ep4",&x);if(!q8||!q84||!rms||!add){E(e,n,x.description.UTF8String);return -1;}id<MTLCommandBuffer>cb=[h->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];uint32_t N=2560;[ce setComputePipelineState:rms];[ce setBuffer:h->emb offset:0 atIndex:0];[ce setBuffer:h->pre_emb_norm.buffer offset:0 atIndex:1];[ce setBuffer:h->en offset:0 atIndex:2];[ce setBytes:&N length:4 atIndex:3];[ce dispatchThreadgroups:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC(ce,q8,&h->fc_emb,h->en,h->ep,2560,2560);N=10240;[ce setComputePipelineState:rms];[ce setBuffer:h->hprev offset:0 atIndex:0];[ce setBuffer:h->pre_hid_norm.buffer offset:0 atIndex:1];[ce setBuffer:h->hn offset:0 atIndex:2];[ce setBytes:&N length:4 atIndex:3];[ce dispatchThreadgroups:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC4(ce,q84,&h->fc_hid,h->hn,h->hp,2560,2560);[ce setComputePipelineState:add];[ce setBuffer:h->hp offset:0 atIndex:0];[ce setBuffer:h->ep offset:0 atIndex:1];[ce setBuffer:h->layer_in offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}}
 double t1=msnow();float layer_out[10240],idx[128],k[512],v[512];qn_qwen4_decode_input in={0};in.hyper_state=h->layer_in.contents;in.indexer_raw_history=h->index_hist;in.key_history=h->key_hist;in.value_history=h->value_hist;in.position=h->seq_offset;in.position_base=h->pos_base;qn_qwen4_decode_output lo={0};lo.hyper_state=layer_out;lo.indexer_raw_key=idx;lo.key_cache=k;lo.value_cache=v;if(qn_qwen4_layer_forward_decode(h->layer,&in,&lo,e,n))return -1;memcpy(h->index_hist+(size_t)h->seq_offset*128,idx,128*4);memcpy(h->key_hist+(size_t)h->seq_offset*512,k,512*4);memcpy(h->value_hist+(size_t)h->seq_offset*512,v,512*4);memcpy(stream_out,layer_out,10240*4);h->seq_offset++;
 double t2=msnow();memcpy(h->hprev.contents,layer_out,10240*4);@autoreleasepool{NSError*x=nil;id q8=P(h,@"q8_mv",&x),gr=P(h,@"group_rms4",&x),sd=P(h,@"silu_div4",&x),si=P(h,@"sigmoid_ip",&x),mx=P(h,@"mix4",&x);if(!q8||!gr||!sd||!si||!mx){E(e,n,x.description.UTF8String);return -1;}id<MTLCommandBuffer>cb=[h->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:gr];[ce setBuffer:h->hprev offset:0 atIndex:0];[ce setBuffer:h->mix_norm.buffer offset:0 atIndex:1];[ce setBuffer:h->mix_xn offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC(ce,q8,&h->mix_down,h->mix_xn,h->mix_lo,320,10240);[ce setComputePipelineState:sd];[ce setBuffer:h->mix_lo offset:0 atIndex:0];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];ENC(ce,q8,&h->mix_up,h->mix_lo,h->mix_w,10240,320);[ce setComputePipelineState:si];[ce setBuffer:h->mix_w offset:0 atIndex:0];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:mx];[ce setBuffer:h->mix_xn offset:0 atIndex:0];[ce setBuffer:h->mix_w offset:0 atIndex:1];[ce setBuffer:h->mixed offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}}
 double lm=0;if(qn_model_io_lm_head(h->io,h->mixed.contents,NULL,&out->draft_token,&lm,e,n))return -1;double t3=msnow();out->preprocess_ms=t1-t0;out->layer_ms=t2-t1;out->mixer_lmhead_ms=t3-t2;out->total_ms=t3-t0;return 0;}

void qn_mtp_head_close(qn_mtp_head*h){if(!h)return;if(h->layer)qn_qwen4_layer_close(h->layer);@autoreleasepool{h->pipes=nil;h->lib=nil;h->queue=nil;h->dev=nil;}for(uint32_t i=0;i<h->map_count;i++)qn_file_map_close(&h->maps[i]);qn_manifest_close(h->manifest);free(h->index_hist);free(h->key_hist);free(h->value_hist);free(h);}
