#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "qn_model_io.h"
#include "qn_manifest.h"
#include "qn_runtime.h"
#include <mach/mach_time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
struct qn_model_io{
 char model_dir[1024];qn_manifest*manifest;qn_file_map maps[3];char shard_names[3][64];uint32_t map_count;
 qn_tensor_meta ew,es,eb;
 __strong id<MTLDevice>dev;__strong id<MTLCommandQueue>queue;__strong id<MTLLibrary>lib;__strong NSMutableDictionary*pipes;
 qn_bf16_metal_view hnorm;qn_affine_metal_view hdown,hup,lm;
 __strong id<MTLBuffer>hb,xn,lo,mw,mixed,logits;
};
static void E(char*e,size_t n,const char*s){if(e&&n)snprintf(e,n,"%s",s?s:"model io error");}
static double nowms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return(double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}inline float sigm(float x){return 1.0f/(1.0f+exp(-x));}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),q*sc+bi);}}a=simd_sum(a);if(lane==0)y[r]=a;}
kernel void group_rms4(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)y[g*2560+j]=x[g*2560+j]*iv*bf16f(w[g*2560+j]);}
kernel void silu_div4(device float*x[[buffer(0)]],uint i[[thread_position_in_grid]]){if(i<320){float z=x[i]*.25f;x[i]=z*sigm(z);}}
kernel void sigmoid_ip(device float*x[[buffer(0)]],uint i[[thread_position_in_grid]]){if(i<10240)x[i]=sigm(x[i]);}
kernel void mix4(device const float*x[[buffer(0)]],device const float*w[[buffer(1)]],device float*y[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<2560){float a=0;for(uint g=0;g<4;g++)a+=x[g*2560+i]*w[g*2560+i];y[i]=a*.25f;}}
)METAL";}
static id<MTLComputePipelineState>P(qn_model_io*m,NSString*n,NSError**e){id p=m->pipes[n];if(p)return p;id f=[m->lib newFunctionWithName:n];p=[m->dev newComputePipelineStateWithFunction:f error:e];if(p)m->pipes[n]=p;return p;}
static qn_file_map*MF(qn_model_io*m,const char*sh,char*e,size_t n){for(uint32_t i=0;i<m->map_count;i++)if(!strcmp(m->shard_names[i],sh))return&m->maps[i];if(m->map_count>=3){E(e,n,"too many model IO shards");return 0;}uint32_t i=m->map_count++;snprintf(m->shard_names[i],64,"%s",sh);char p[1200];snprintf(p,sizeof(p),"%s/%s",m->model_dir,sh);m->maps[i].fd=-1;if(qn_file_map_open(&m->maps[i],p,e,n))return 0;return&m->maps[i];}
static int T(qn_model_io*m,const char*n,qn_tensor_meta*t,char*e,size_t z){return qn_manifest_tensor(m->manifest,n,t,e,z);}
static int BF(qn_model_io*m,const char*n,uint64_t N,qn_bf16_metal_view*v,char*e,size_t z){qn_tensor_meta t;if(T(m,n,&t,e,z))return-1;qn_file_map*f=MF(m,t.shard,e,z);return f?qn_bf16_make_view(m->dev,f,t.file_offset,N,v,e,z):-1;}
static int AF(qn_model_io*m,const char*base,uint32_t O,uint32_t I,qn_affine_metal_view*v,char*e,size_t z){char k[256];qn_tensor_meta w,s,b;snprintf(k,256,"%s.weight",base);if(T(m,k,&w,e,z))return-1;snprintf(k,256,"%s.scales",base);if(T(m,k,&s,e,z))return-1;snprintf(k,256,"%s.biases",base);if(T(m,k,&b,e,z))return-1;qn_file_map*f=MF(m,w.shard,e,z);qn_affine_desc d={w.file_offset,s.file_offset,b.file_offset,O,I,64,8};return f?qn_affine_make_view(m->dev,f,&d,v,e,z):-1;}
static void ENC(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
static float bf16(uint16_t x){uint32_t u=(uint32_t)x<<16;float f;memcpy(&f,&u,4);return f;}
int qn_model_io_open(qn_model_io**out,const qn_model_io_config*c,char*e,size_t n){if(!out||!c){E(e,n,"invalid config");return-1;}qn_model_io*m=calloc(1,sizeof(*m));snprintf(m->model_dir,sizeof(m->model_dir),"%s",c->model_dir);for(int i=0;i<3;i++)m->maps[i].fd=-1;if(qn_manifest_open(&m->manifest,c->manifest_path,e,n)){free(m);return-1;}@autoreleasepool{m->dev=MTLCreateSystemDefaultDevice();m->queue=[m->dev newCommandQueue];NSError*x=nil;m->lib=[m->dev newLibraryWithSource:src() options:nil error:&x];if(!m->lib){E(e,n,x.description.UTF8String);qn_model_io_close(m);return-1;}m->pipes=[NSMutableDictionary dictionary];for(NSString*k in @[@"q8_mv",@"group_rms4",@"silu_div4",@"sigmoid_ip",@"mix4"])if(!P(m,k,&x)){E(e,n,x.description.UTF8String);qn_model_io_close(m);return-1;}if(T(m,"language_model.model.embed_tokens.weight",&m->ew,e,n)||T(m,"language_model.model.embed_tokens.scales",&m->es,e,n)||T(m,"language_model.model.embed_tokens.biases",&m->eb,e,n)){qn_model_io_close(m);return-1;}MF(m,m->ew.shard,e,n);if(BF(m,"language_model.model.hyper_connection_mixer.hc_norm.weight",10240,&m->hnorm,e,n)||AF(m,"language_model.model.hyper_connection_mixer.input_mix_weight_down",320,10240,&m->hdown,e,n)||AF(m,"language_model.model.hyper_connection_mixer.input_mix_weight_up",10240,320,&m->hup,e,n)||AF(m,"language_model.lm_head",248320,2560,&m->lm,e,n)){qn_model_io_close(m);return-1;}m->hb=[m->dev newBufferWithLength:40960 options:MTLResourceStorageModeShared];m->xn=[m->dev newBufferWithLength:40960 options:MTLResourceStorageModeShared];m->lo=[m->dev newBufferWithLength:1280 options:MTLResourceStorageModeShared];m->mw=[m->dev newBufferWithLength:40960 options:MTLResourceStorageModeShared];m->mixed=[m->dev newBufferWithLength:10240 options:MTLResourceStorageModeShared];m->logits=[m->dev newBufferWithLength:248320*4 options:MTLResourceStorageModeShared];}*out=m;return 0;}
int qn_model_io_embed(qn_model_io*m,uint32_t tok,float out[2560],char*e,size_t n){if(!m||!out||tok>=248320){E(e,n,"invalid token");return-1;}qn_file_map*f=MF(m,m->ew.shard,e,n);uint32_t*w=(uint32_t*)((uint8_t*)f->base+m->ew.file_offset+(uint64_t)tok*1280);uint16_t*s=(uint16_t*)((uint8_t*)f->base+m->es.file_offset+(uint64_t)tok*80),*b=(uint16_t*)((uint8_t*)f->base+m->eb.file_offset+(uint64_t)tok*80);for(int j=0;j<2560;j++)out[j]=(float)((w[j/8]>>(4*(j&7)))&15)*bf16(s[j/64])+bf16(b[j/64]);return 0;}
int qn_model_io_logits(qn_model_io*m,const float*h,float*logits,uint32_t*argmax,double*elapsed,char*e,size_t n){if(!m||!h){E(e,n,"invalid logits args");return-1;}@autoreleasepool{memcpy(m->hb.contents,h,40960);NSError*x=nil;id q8=P(m,@"q8_mv",&x),gr=P(m,@"group_rms4",&x),sd=P(m,@"silu_div4",&x),si=P(m,@"sigmoid_ip",&x),mx=P(m,@"mix4",&x);double t0=nowms();id<MTLCommandBuffer>cb=[m->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:gr];[ce setBuffer:m->hb offset:0 atIndex:0];[ce setBuffer:m->hnorm.buffer offset:0 atIndex:1];[ce setBuffer:m->xn offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];ENC(ce,q8,&m->hdown,m->xn,m->lo,320,10240);[ce setComputePipelineState:sd];[ce setBuffer:m->lo offset:0 atIndex:0];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];ENC(ce,q8,&m->hup,m->lo,m->mw,10240,320);[ce setComputePipelineState:si];[ce setBuffer:m->mw offset:0 atIndex:0];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:mx];[ce setBuffer:m->xn offset:0 atIndex:0];[ce setBuffer:m->mw offset:0 atIndex:1];[ce setBuffer:m->mixed offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];ENC(ce,q8,&m->lm,m->mixed,m->logits,248320,2560);[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return-1;}float*lp=m->logits.contents;if(logits)memcpy(logits,lp,248320*4);if(argmax){uint32_t bi=0;float bv=lp[0];for(uint32_t i=1;i<248320;i++)if(lp[i]>bv){bv=lp[i];bi=i;}*argmax=bi;}if(elapsed)*elapsed=nowms()-t0;}return 0;}

int qn_model_io_lm_head(qn_model_io*m,const float*hidden,float*logits,uint32_t*argmax,double*elapsed,char*e,size_t n){if(!m||!hidden){E(e,n,"invalid lm head args");return-1;}@autoreleasepool{memcpy(m->mixed.contents,hidden,2560*4);NSError*x=nil;id q8=P(m,@"q8_mv",&x);if(!q8){E(e,n,x.description.UTF8String);return-1;}double t0=nowms();id<MTLCommandBuffer>cb=[m->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];ENC(ce,q8,&m->lm,m->mixed,m->logits,248320,2560);[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return-1;}float*lp=m->logits.contents;if(logits)memcpy(logits,lp,248320*4);if(argmax){uint32_t bi=0;float bv=lp[0];for(uint32_t i=1;i<248320;i++)if(lp[i]>bv){bv=lp[i];bi=i;}*argmax=bi;}if(elapsed)*elapsed=nowms()-t0;}return 0;}
void qn_model_io_close(qn_model_io*m){if(!m)return;@autoreleasepool{m->pipes=nil;m->lib=nil;m->queue=nil;m->dev=nil;}for(uint32_t i=0;i<m->map_count;i++)qn_file_map_close(&m->maps[i]);qn_manifest_close(m->manifest);free(m);}
