#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "qn_ple_layer.h"
#include "qn_manifest.h"
#include "qn_runtime.h"
#include <mach/mach_time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

struct qn_ple_layer {
 char model_dir[1024]; qn_manifest *manifest; qn_file_map maps[2], ngram; char shard_names[2][64]; uint32_t map_count;
 uint64_t ng_base,ng_wo,ng_so,ng_bo,ng_rows;
 int64_t mult[3],sizes[16],offs[16];
 __strong id<MTLDevice> dev; __strong id<MTLCommandQueue> queue; __strong id<MTLLibrary> lib; __strong NSMutableDictionary *pipes;
 qn_affine_metal_view key_proj,value_proj; qn_bf16_metal_view norm_key,norm_query,norm_conv,conv_weight;
 __strong id<MTLBuffer> emb,key,val,query,gated,convnorm,convstate,convout,out;
};
static void E(char*e,size_t n,const char*s){if(e&&n)snprintf(e,n,"%s",s?s:"PLE error");}
static double nowms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return (double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}inline float sigm(float x){return 1.0f/(1.0f+exp(-x));}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),q*sc+bi);}}a=simd_sum(a);if(lane==0)y[r]=a;}
kernel void group_norm(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)y[g*2560+j]=x[g*2560+j]*iv*bf16f(w[g*2560+j]);}
kernel void gate_value(device const float*k[[buffer(0)]],device const float*q[[buffer(1)]],device const float*v[[buffer(2)]],device float*y[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float a=0;for(uint j=lane;j<2560;j+=32)a+=k[g*2560+j]*q[g*2560+j];a=simd_sum(a)*0.01976423537605237f;if(lane==0){float z=copysign(sqrt(max(fabs(a),1e-6f)),a);for(uint j=0;j<2560;j++)y[g*2560+j]=v[j]*sigm(z);}}
kernel void ple_conv(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*state[[buffer(2)]],device float*y[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<10240){uint b=i*9;float a=state[b]*bf16f(w[i*4])+state[b+3]*bf16f(w[i*4+1])+state[b+6]*bf16f(w[i*4+2])+x[i]*bf16f(w[i*4+3]);for(uint j=0;j<8;j++)state[b+j]=state[b+j+1];state[b+8]=x[i];y[i]=a*sigm(a);}}
kernel void add2(device const float*a[[buffer(0)]],device const float*b[[buffer(1)]],device float*y[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<10240)y[i]=a[i]+b[i];}
kernel void q8_rows(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],constant uint&T[[buffer(7)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint z=tid/32,t=z/O,r=z-t*O;if(t>=T)return;device const float*xr=x+t*I;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(xr[k],xr[k+1],xr[k+2],xr[k+3]),q*sc+bi);}}a=simd_sum(a);if(lane==0)y[t*O+r]=a;}
kernel void group_norm_rows(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],constant uint&T[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint z=tid/32,t=z/4,g=z-t*4;if(t>=T)return;device const float*xr=x+t*10240;device float*yr=y+t*10240;float ss=0;for(uint j=lane;j<2560;j+=32){float v=xr[g*2560+j];ss+=v*v;}ss=simd_sum(ss);float iv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)yr[g*2560+j]=xr[g*2560+j]*iv*bf16f(w[g*2560+j]);}
kernel void gate_value_rows(device const float*k[[buffer(0)]],device const float*q[[buffer(1)]],device const float*v[[buffer(2)]],device float*y[[buffer(3)]],constant uint&T[[buffer(4)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint z=tid/32,t=z/4,g=z-t*4;if(t>=T)return;device const float*kr=k+t*10240;device const float*qr=q+t*10240;device const float*vr=v+t*2560;device float*yr=y+t*10240;float a=0;for(uint j=lane;j<2560;j+=32)a+=kr[g*2560+j]*qr[g*2560+j];a=simd_sum(a)*0.01976423537605237f;if(lane==0){float z0=copysign(sqrt(max(fabs(a),1e-6f)),a);float sg=sigm(z0);for(uint j=0;j<2560;j++)yr[g*2560+j]=vr[j]*sg;}}
inline float bfroundf(float x){uint u=as_type<uint>(x);u+=0x7fffu+((u>>16)&1u);u&=0xffff0000u;return as_type<float>(u);}
kernel void ple_conv_seq(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*state[[buffer(2)]],device float*y[[buffer(3)]],constant uint&T[[buffer(4)]],uint i[[thread_position_in_grid]]){if(i>=10240)return;uint b=i*9;float s0=state[b],s1=state[b+1],s2=state[b+2],s3=state[b+3],s4=state[b+4],s5=state[b+5],s6=state[b+6],s7=state[b+7],s8=state[b+8];for(uint t=0;t<T;t++){float v=x[t*10240+i];float a=s0*bf16f(w[i*4])+s3*bf16f(w[i*4+1])+s6*bf16f(w[i*4+2])+v*bf16f(w[i*4+3]);y[t*10240+i]=a*sigm(a);s0=s1;s1=s2;s2=s3;s3=s4;s4=s5;s5=s6;s6=s7;s7=s8;s8=bfroundf(v);}state[b]=s0;state[b+1]=s1;state[b+2]=s2;state[b+3]=s3;state[b+4]=s4;state[b+5]=s5;state[b+6]=s6;state[b+7]=s7;state[b+8]=s8;}
kernel void add2_rows(device const float*a[[buffer(0)]],device const float*b[[buffer(1)]],device float*y[[buffer(2)]],constant uint&N[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<N)y[i]=a[i]+b[i];}
)METAL";}
static id<MTLComputePipelineState>P(qn_ple_layer*l,NSString*n,NSError**e){id p=l->pipes[n];if(p)return p;id f=[l->lib newFunctionWithName:n];p=[l->dev newComputePipelineStateWithFunction:f error:e];if(p)l->pipes[n]=p;return p;}
static qn_file_map*MF(qn_ple_layer*l,const char*sh,char*e,size_t n){for(uint32_t i=0;i<l->map_count;i++)if(!strcmp(l->shard_names[i],sh))return &l->maps[i];if(l->map_count>=2){E(e,n,"too many PLE shards");return 0;}uint32_t i=l->map_count++;snprintf(l->shard_names[i],64,"%s",sh);char p[1200];snprintf(p,sizeof(p),"%s/%s",l->model_dir,sh);l->maps[i].fd=-1;if(qn_file_map_open(&l->maps[i],p,e,n))return 0;return &l->maps[i];}
static int TM(qn_ple_layer*l,const char*s,qn_tensor_meta*t,char*e,size_t n){return qn_manifest_layer_tensor(l->manifest,1,s,t,e,n);}
static int BF(qn_ple_layer*l,const char*s,uint64_t N,qn_bf16_metal_view*v,char*e,size_t n){qn_tensor_meta t;if(TM(l,s,&t,e,n))return -1;qn_file_map*m=MF(l,t.shard,e,n);return m?qn_bf16_make_view(l->dev,m,t.file_offset,N,v,e,n):-1;}
static int AF(qn_ple_layer*l,const char*base,uint32_t O,uint32_t I,qn_affine_metal_view*v,char*e,size_t n){char k[256];qn_tensor_meta w,s,b;snprintf(k,256,"%s.weight",base);if(TM(l,k,&w,e,n))return -1;snprintf(k,256,"%s.scales",base);if(TM(l,k,&s,e,n))return -1;snprintf(k,256,"%s.biases",base);if(TM(l,k,&b,e,n))return -1;qn_file_map*m=MF(l,w.shard,e,n);qn_affine_desc d={w.file_offset,s.file_offset,b.file_offset,O,I,64,8};return m?qn_affine_make_view(l->dev,m,&d,v,e,n):-1;}
static void ENC(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
static void ENC_ROWS(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I,uint32_t T){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce setBytes:&T length:4 atIndex:7];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
static int64_t mod_floor(int64_t x,int64_t m){int64_t r=x%m;return r<0?r+m:r;}
static float bf16(uint16_t x){uint32_t u=(uint32_t)x<<16;float f;memcpy(&f,&u,4);return f;}
static float bfround_cpu(float x){uint32_t u;memcpy(&u,&x,4);u+=0x7fffu+((u>>16)&1u);u&=0xffff0000u;memcpy(&x,&u,4);return x;}
static void bfround_vec(float*x,size_t n){for(size_t i=0;i<n;i++)x[i]=bfround_cpu(x[i]);}
int qn_ple_layer_open(qn_ple_layer**out,const qn_ple_config*c,char*e,size_t n){if(!out||!c){E(e,n,"invalid config");return -1;}qn_ple_layer*l=calloc(1,sizeof(*l));snprintf(l->model_dir,sizeof(l->model_dir),"%s",c->model_dir);for(int i=0;i<2;i++)l->maps[i].fd=-1;l->ngram.fd=-1;if(qn_manifest_open(&l->manifest,c->manifest_path,e,n)||qn_file_map_open(&l->ngram,c->ngram_table_path,e,n)){qn_ple_layer_close(l);return -1;}@autoreleasepool{l->dev=MTLCreateSystemDefaultDevice();l->queue=[l->dev newCommandQueue];NSError*x=nil;l->lib=[l->dev newLibraryWithSource:src() options:nil error:&x];if(!l->lib){E(e,n,x.description.UTF8String);qn_ple_layer_close(l);return -1;}l->pipes=[NSMutableDictionary dictionary];for(NSString*k in @[@"q8_mv",@"group_norm",@"gate_value",@"ple_conv",@"add2",@"q8_rows",@"group_norm_rows",@"gate_value_rows",@"ple_conv_seq",@"add2_rows"])if(!P(l,k,&x)){E(e,n,x.description.UTF8String);qn_ple_layer_close(l);return -1;}if(AF(l,"ple.key_proj",10240,2560,&l->key_proj,e,n)||AF(l,"ple.value_proj",2560,2560,&l->value_proj,e,n)||BF(l,"ple.norm_key.weight",10240,&l->norm_key,e,n)||BF(l,"ple.norm_query.weight",10240,&l->norm_query,e,n)||BF(l,"ple.norm_conv.weight",10240,&l->norm_conv,e,n)||BF(l,"ple.conv1d.weight",40960,&l->conv_weight,e,n)){qn_ple_layer_close(l);return -1;}
 qn_tensor_meta t; if(TM(l,"ple.ple_embedding.layer_multipliers",&t,e,n))return -1;qn_file_map*m=MF(l,t.shard,e,n);memcpy(l->mult,(uint8_t*)m->base+t.file_offset,24);if(TM(l,"ple.ple_embedding.ngram_heads_vocab_sizes",&t,e,n))return -1;m=MF(l,t.shard,e,n);memcpy(l->sizes,(uint8_t*)m->base+t.file_offset,128);if(TM(l,"ple.ple_embedding.ngram_heads_offsets",&t,e,n))return -1;m=MF(l,t.shard,e,n);memcpy(l->offs,(uint8_t*)m->base+t.file_offset,128);
 uint64_t hl=0;memcpy(&hl,l->ngram.base,8);l->ng_base=8+hl;NSData*jd=[NSData dataWithBytes:(uint8_t*)l->ngram.base+8 length:hl];NSDictionary*j=[NSJSONSerialization JSONObjectWithData:jd options:0 error:&x];NSDictionary*w=j[@"weight"],*s=j[@"scales"],*b=j[@"biases"];l->ng_rows=[w[@"shape"][0] unsignedLongLongValue];l->ng_wo=[w[@"data_offsets"][0] unsignedLongLongValue];l->ng_so=[s[@"data_offsets"][0] unsignedLongLongValue];l->ng_bo=[b[@"data_offsets"][0] unsignedLongLongValue];
 #define B(name,N) l->name=[l->dev newBufferWithLength:(N) options:MTLResourceStorageModeShared]
 B(emb,10240);B(key,40960);B(val,10240);B(query,40960);B(gated,40960);B(convnorm,40960);B(convstate,10240*9*4);B(convout,40960);B(out,40960);
 #undef B
 }*out=l;return 0;}
int qn_ple_layer_forward(qn_ple_layer*l,const qn_ple_input*in,qn_ple_output*out,char*e,size_t n){if(!l||!in||!out||!in->hyper_state||!in->conv_state||!out->ple_output){E(e,n,"invalid forward");return -1;}double t0=nowms();int64_t cur=in->token_history[2],p1=in->token_history[1],p2=in->token_history[0];const int64_t eos=248044;if(p1==eos)p2=eos;float*ev=l->emb.contents;for(int h=0;h<16;h++){int64_t mix=(cur*l->mult[0])^(p1*l->mult[1]);if(h>=8)mix^=(p2*l->mult[2]);int64_t rid=mod_floor(mix,l->sizes[h])+l->offs[h];if(rid<0||(uint64_t)rid>=l->ng_rows){E(e,n,"ngram row out of range");return -1;}out->ngram_ids[h]=rid;uint8_t*base=(uint8_t*)l->ngram.base+l->ng_base;uint32_t*w=(uint32_t*)(base+l->ng_wo+(uint64_t)rid*80);uint16_t*s=(uint16_t*)(base+l->ng_so+(uint64_t)rid*10),*b=(uint16_t*)(base+l->ng_bo+(uint64_t)rid*10);for(int j=0;j<160;j++){uint32_t q=w[j>>3];ev[h*160+j]=bfround_cpu((float)((q>>(4*(j&7)))&15)*bf16(s[j/32])+bf16(b[j/32]));}}
 @autoreleasepool{memcpy(l->query.contents,in->hyper_state,40960);memcpy(l->convstate.contents,in->conv_state,10240*9*4);NSError*x=nil;id q8=P(l,@"q8_mv",&x),gn=P(l,@"group_norm",&x),gv=P(l,@"gate_value",&x),cv=P(l,@"ple_conv",&x),ad=P(l,@"add2",&x);id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];ENC(ce,q8,&l->key_proj,l->emb,l->key,10240,2560);ENC(ce,q8,&l->value_proj,l->emb,l->val,2560,2560);[ce setComputePipelineState:gn];[ce setBuffer:l->key offset:0 atIndex:0];[ce setBuffer:l->norm_key.buffer offset:0 atIndex:1];[ce setBuffer:l->key offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gn];[ce setBuffer:l->query offset:0 atIndex:0];[ce setBuffer:l->norm_query.buffer offset:0 atIndex:1];[ce setBuffer:l->query offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gv];[ce setBuffer:l->key offset:0 atIndex:0];[ce setBuffer:l->query offset:0 atIndex:1];[ce setBuffer:l->val offset:0 atIndex:2];[ce setBuffer:l->gated offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gn];[ce setBuffer:l->gated offset:0 atIndex:0];[ce setBuffer:l->norm_conv.buffer offset:0 atIndex:1];[ce setBuffer:l->convnorm offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:cv];[ce setBuffer:l->convnorm offset:0 atIndex:0];[ce setBuffer:l->conv_weight.buffer offset:0 atIndex:1];[ce setBuffer:l->convstate offset:0 atIndex:2];[ce setBuffer:l->convout offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:ad];[ce setBuffer:l->gated offset:0 atIndex:0];[ce setBuffer:l->convout offset:0 atIndex:1];[ce setBuffer:l->out offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}bfround_vec((float*)l->out.contents,10240);bfround_vec((float*)l->convstate.contents,10240*9);memcpy(out->ple_output,l->out.contents,40960);memcpy(in->conv_state,l->convstate.contents,10240*9*4);out->elapsed_ms=nowms()-t0;}return 0;}

int qn_ple_layer_forward_batch(qn_ple_layer*l,const float*hyper_states,const int64_t*token_ids,uint32_t T,int64_t hist[2],float*conv_state,float*ple_outputs,char*e,size_t n){
 if(!l||!hyper_states||!token_ids||!T||!hist||!conv_state||!ple_outputs){E(e,n,"invalid batch PLE args");return -1;}
 size_t ne=(size_t)T*2560,n10=(size_t)T*10240;float*embs=malloc(ne*sizeof(float));if(!embs){E(e,n,"batch PLE embedding allocation failed");return -1;}
 int64_t p2=hist[0],p1=hist[1],eos=248044;
 for(uint32_t t=0;t<T;t++){int64_t cur=token_ids[t];if(p1==eos)p2=eos;float*ev=embs+(size_t)t*2560;for(int h=0;h<16;h++){int64_t mix=(cur*l->mult[0])^(p1*l->mult[1]);if(h>=8)mix^=(p2*l->mult[2]);int64_t rid=mod_floor(mix,l->sizes[h])+l->offs[h];if(rid<0||(uint64_t)rid>=l->ng_rows){free(embs);E(e,n,"batch ngram row out of range");return -1;}uint8_t*base=(uint8_t*)l->ngram.base+l->ng_base;uint32_t*w=(uint32_t*)(base+l->ng_wo+(uint64_t)rid*80);uint16_t*sc=(uint16_t*)(base+l->ng_so+(uint64_t)rid*10),*bi=(uint16_t*)(base+l->ng_bo+(uint64_t)rid*10);for(int j=0;j<160;j++){uint32_t q=w[j>>3];ev[h*160+j]=bfround_cpu((float)((q>>(4*(j&7)))&15)*bf16(sc[j/32])+bf16(bi[j/32]));}}p2=p1;p1=cur;}
 @autoreleasepool{
#define PB(name,count) id<MTLBuffer> name=[l->dev newBufferWithLength:(NSUInteger)(count)*sizeof(float) options:MTLResourceStorageModeShared];if(!name){free(embs);E(e,n,"batch PLE buffer allocation failed");return -1;}
  PB(eb,ne);PB(key,n10);PB(val,ne);PB(query,n10);PB(gated,n10);PB(convnorm,n10);PB(convout,n10);PB(outb,n10);PB(state,(size_t)10240*9);
#undef PB
  memcpy(eb.contents,embs,ne*sizeof(float));memcpy(query.contents,hyper_states,n10*sizeof(float));memcpy(state.contents,conv_state,(size_t)10240*9*sizeof(float));free(embs);
  NSError*x=nil;id qr=P(l,@"q8_rows",&x),gn=P(l,@"group_norm_rows",&x),gv=P(l,@"gate_value_rows",&x),cv=P(l,@"ple_conv_seq",&x),ad=P(l,@"add2_rows",&x);if(!qr||!gn||!gv||!cv||!ad){E(e,n,x.description.UTF8String);return -1;}
  uint32_t N=(uint32_t)n10;id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];
  ENC_ROWS(ce,qr,&l->key_proj,eb,key,10240,2560,T);ENC_ROWS(ce,qr,&l->value_proj,eb,val,2560,2560,T);
  [ce setComputePipelineState:gn];[ce setBuffer:key offset:0 atIndex:0];[ce setBuffer:l->norm_key.buffer offset:0 atIndex:1];[ce setBuffer:key offset:0 atIndex:2];[ce setBytes:&T length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*4*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  [ce setComputePipelineState:gn];[ce setBuffer:query offset:0 atIndex:0];[ce setBuffer:l->norm_query.buffer offset:0 atIndex:1];[ce setBuffer:query offset:0 atIndex:2];[ce setBytes:&T length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*4*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  [ce setComputePipelineState:gv];[ce setBuffer:key offset:0 atIndex:0];[ce setBuffer:query offset:0 atIndex:1];[ce setBuffer:val offset:0 atIndex:2];[ce setBuffer:gated offset:0 atIndex:3];[ce setBytes:&T length:4 atIndex:4];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*4*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  [ce setComputePipelineState:gn];[ce setBuffer:gated offset:0 atIndex:0];[ce setBuffer:l->norm_conv.buffer offset:0 atIndex:1];[ce setBuffer:convnorm offset:0 atIndex:2];[ce setBytes:&T length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)T*4*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  [ce setComputePipelineState:cv];[ce setBuffer:convnorm offset:0 atIndex:0];[ce setBuffer:l->conv_weight.buffer offset:0 atIndex:1];[ce setBuffer:state offset:0 atIndex:2];[ce setBuffer:convout offset:0 atIndex:3];[ce setBytes:&T length:4 atIndex:4];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  [ce setComputePipelineState:ad];[ce setBuffer:gated offset:0 atIndex:0];[ce setBuffer:convout offset:0 atIndex:1];[ce setBuffer:outb offset:0 atIndex:2];[ce setBytes:&N length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(N,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  [ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}bfround_vec((float*)outb.contents,n10);memcpy(ple_outputs,outb.contents,n10*sizeof(float));memcpy(conv_state,state.contents,(size_t)10240*9*sizeof(float));hist[0]=p2;hist[1]=p1;
 }
 return 0;
}

void qn_ple_layer_close(qn_ple_layer*l){if(!l)return;@autoreleasepool{l->pipes=nil;l->lib=nil;l->queue=nil;l->dev=nil;}for(uint32_t i=0;i<l->map_count;i++)qn_file_map_close(&l->maps[i]);qn_file_map_close(&l->ngram);qn_manifest_close(l->manifest);free(l);}
