#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "qn_ple_layer.h"
#include "qn_manifest.h"
#include "qn_runtime.h"
#include <mach/mach_time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

struct qn_ple_layer {
 char model_dir[1024]; qn_manifest *manifest; qn_file_map maps[2], ngram; char shard_names[2][64]; uint32_t map_count;
 uint64_t ng_base,ng_wo,ng_so,ng_bo,ng_rows;
 int64_t mult[3],sizes[16],offs[16];
 __strong id<MTLDevice> dev; __strong id<MTLCommandQueue> queue; __strong id<MTLLibrary> lib; __strong NSMutableDictionary *pipes;
 qn_affine_metal_view key_proj,value_proj; qn_bf16_metal_view norm_key,norm_query,norm_conv,conv_weight;
 __strong id<MTLBuffer> emb,key,val,query,gated,convnorm,convstate,convout,out;
};
static void E(char*e,size_t n,const char*s){if(e&&n)snprintf(e,n,"%s",s?s:"PLE error");}
static double nowms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return (double)mach_absolute_time()*tb.numer/tb.denom/1e6;}
static NSString*src(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;inline float bf16f(ushort v){return as_type<float>((uint)v<<16);}inline float sigm(float x){return 1.0f/(1.0f+exp(-x));}
kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*s[[buffer(1)]],device const ushort*b[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;for(uint g=0;g<G;g++){float sc=bf16f(s[r*G+g]),bi=bf16f(b[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),q*sc+bi);}}a=simd_sum(a);if(lane==0)y[r]=a;}
kernel void group_norm(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float iv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)y[g*2560+j]=x[g*2560+j]*iv*bf16f(w[g*2560+j]);}
kernel void gate_value(device const float*k[[buffer(0)]],device const float*q[[buffer(1)]],device const float*v[[buffer(2)]],device float*y[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float a=0;for(uint j=lane;j<2560;j+=32)a+=k[g*2560+j]*q[g*2560+j];a=simd_sum(a)*0.01976423537605237f;if(lane==0){float z=copysign(sqrt(max(fabs(a),1e-6f)),a);for(uint j=0;j<2560;j++)y[g*2560+j]=v[j]*sigm(z);}}
kernel void ple_conv(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*state[[buffer(2)]],device float*y[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<10240){uint b=i*9;float a=state[b]*bf16f(w[i*4])+state[b+3]*bf16f(w[i*4+1])+state[b+6]*bf16f(w[i*4+2])+x[i]*bf16f(w[i*4+3]);for(uint j=0;j<8;j++)state[b+j]=state[b+j+1];state[b+8]=x[i];y[i]=a*sigm(a);}}
kernel void add2(device const float*a[[buffer(0)]],device const float*b[[buffer(1)]],device float*y[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<10240)y[i]=a[i]+b[i];}
)METAL";}
static id<MTLComputePipelineState>P(qn_ple_layer*l,NSString*n,NSError**e){id p=l->pipes[n];if(p)return p;id f=[l->lib newFunctionWithName:n];p=[l->dev newComputePipelineStateWithFunction:f error:e];if(p)l->pipes[n]=p;return p;}
static qn_file_map*MF(qn_ple_layer*l,const char*sh,char*e,size_t n){for(uint32_t i=0;i<l->map_count;i++)if(!strcmp(l->shard_names[i],sh))return &l->maps[i];if(l->map_count>=2){E(e,n,"too many PLE shards");return 0;}uint32_t i=l->map_count++;snprintf(l->shard_names[i],64,"%s",sh);char p[1200];snprintf(p,sizeof(p),"%s/%s",l->model_dir,sh);l->maps[i].fd=-1;if(qn_file_map_open(&l->maps[i],p,e,n))return 0;return &l->maps[i];}
static int TM(qn_ple_layer*l,const char*s,qn_tensor_meta*t,char*e,size_t n){return qn_manifest_layer_tensor(l->manifest,1,s,t,e,n);}
static int BF(qn_ple_layer*l,const char*s,uint64_t N,qn_bf16_metal_view*v,char*e,size_t n){qn_tensor_meta t;if(TM(l,s,&t,e,n))return -1;qn_file_map*m=MF(l,t.shard,e,n);return m?qn_bf16_make_view(l->dev,m,t.file_offset,N,v,e,n):-1;}
static int AF(qn_ple_layer*l,const char*base,uint32_t O,uint32_t I,qn_affine_metal_view*v,char*e,size_t n){char k[256];qn_tensor_meta w,s,b;snprintf(k,256,"%s.weight",base);if(TM(l,k,&w,e,n))return -1;snprintf(k,256,"%s.scales",base);if(TM(l,k,&s,e,n))return -1;snprintf(k,256,"%s.biases",base);if(TM(l,k,&b,e,n))return -1;qn_file_map*m=MF(l,w.shard,e,n);qn_affine_desc d={w.file_offset,s.file_offset,b.file_offset,O,I,64,8};return m?qn_affine_make_view(l->dev,m,&d,v,e,n):-1;}
static void ENC(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>p,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){[ce setComputePipelineState:p];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];}
static int64_t mod_floor(int64_t x,int64_t m){int64_t r=x%m;return r<0?r+m:r;}
static float bf16(uint16_t x){uint32_t u=(uint32_t)x<<16;float f;memcpy(&f,&u,4);return f;}
int qn_ple_layer_open(qn_ple_layer**out,const qn_ple_config*c,char*e,size_t n){if(!out||!c){E(e,n,"invalid config");return -1;}qn_ple_layer*l=calloc(1,sizeof(*l));snprintf(l->model_dir,sizeof(l->model_dir),"%s",c->model_dir);for(int i=0;i<2;i++)l->maps[i].fd=-1;l->ngram.fd=-1;if(qn_manifest_open(&l->manifest,c->manifest_path,e,n)||qn_file_map_open(&l->ngram,c->ngram_table_path,e,n)){qn_ple_layer_close(l);return -1;}@autoreleasepool{l->dev=MTLCreateSystemDefaultDevice();l->queue=[l->dev newCommandQueue];NSError*x=nil;l->lib=[l->dev newLibraryWithSource:src() options:nil error:&x];if(!l->lib){E(e,n,x.description.UTF8String);qn_ple_layer_close(l);return -1;}l->pipes=[NSMutableDictionary dictionary];for(NSString*k in @[@"q8_mv",@"group_norm",@"gate_value",@"ple_conv",@"add2"])if(!P(l,k,&x)){E(e,n,x.description.UTF8String);qn_ple_layer_close(l);return -1;}if(AF(l,"ple.key_proj",10240,2560,&l->key_proj,e,n)||AF(l,"ple.value_proj",2560,2560,&l->value_proj,e,n)||BF(l,"ple.norm_key.weight",10240,&l->norm_key,e,n)||BF(l,"ple.norm_query.weight",10240,&l->norm_query,e,n)||BF(l,"ple.norm_conv.weight",10240,&l->norm_conv,e,n)||BF(l,"ple.conv1d.weight",40960,&l->conv_weight,e,n)){qn_ple_layer_close(l);return -1;}
 qn_tensor_meta t; if(TM(l,"ple.ple_embedding.layer_multipliers",&t,e,n))return -1;qn_file_map*m=MF(l,t.shard,e,n);memcpy(l->mult,(uint8_t*)m->base+t.file_offset,24);if(TM(l,"ple.ple_embedding.ngram_heads_vocab_sizes",&t,e,n))return -1;m=MF(l,t.shard,e,n);memcpy(l->sizes,(uint8_t*)m->base+t.file_offset,128);if(TM(l,"ple.ple_embedding.ngram_heads_offsets",&t,e,n))return -1;m=MF(l,t.shard,e,n);memcpy(l->offs,(uint8_t*)m->base+t.file_offset,128);
 uint64_t hl=0;memcpy(&hl,l->ngram.base,8);l->ng_base=8+hl;NSData*jd=[NSData dataWithBytes:(uint8_t*)l->ngram.base+8 length:hl];NSDictionary*j=[NSJSONSerialization JSONObjectWithData:jd options:0 error:&x];NSDictionary*w=j[@"weight"],*s=j[@"scales"],*b=j[@"biases"];l->ng_rows=[w[@"shape"][0] unsignedLongLongValue];l->ng_wo=[w[@"data_offsets"][0] unsignedLongLongValue];l->ng_so=[s[@"data_offsets"][0] unsignedLongLongValue];l->ng_bo=[b[@"data_offsets"][0] unsignedLongLongValue];
 #define B(name,N) l->name=[l->dev newBufferWithLength:(N) options:MTLResourceStorageModeShared]
 B(emb,10240);B(key,40960);B(val,10240);B(query,40960);B(gated,40960);B(convnorm,40960);B(convstate,10240*9*4);B(convout,40960);B(out,40960);
 #undef B
 }*out=l;return 0;}
int qn_ple_layer_forward(qn_ple_layer*l,const qn_ple_input*in,qn_ple_output*out,char*e,size_t n){if(!l||!in||!out||!in->hyper_state||!in->conv_state||!out->ple_output){E(e,n,"invalid forward");return -1;}double t0=nowms();int64_t cur=in->token_history[2],p1=in->token_history[1],p2=in->token_history[0];float*ev=l->emb.contents;for(int h=0;h<16;h++){int64_t mix=(cur*l->mult[0])^(p1*l->mult[1]);if(h>=8)mix^=(p2*l->mult[2]);int64_t rid=mod_floor(mix,l->sizes[h])+l->offs[h];if(rid<0||(uint64_t)rid>=l->ng_rows){E(e,n,"ngram row out of range");return -1;}out->ngram_ids[h]=rid;uint8_t*base=(uint8_t*)l->ngram.base+l->ng_base;uint32_t*w=(uint32_t*)(base+l->ng_wo+(uint64_t)rid*80);uint16_t*s=(uint16_t*)(base+l->ng_so+(uint64_t)rid*10),*b=(uint16_t*)(base+l->ng_bo+(uint64_t)rid*10);for(int j=0;j<160;j++){uint32_t q=w[j>>3];ev[h*160+j]=(float)((q>>(4*(j&7)))&15)*bf16(s[j/32])+bf16(b[j/32]);}}
 @autoreleasepool{memcpy(l->query.contents,in->hyper_state,40960);memcpy(l->convstate.contents,in->conv_state,10240*9*4);NSError*x=nil;id q8=P(l,@"q8_mv",&x),gn=P(l,@"group_norm",&x),gv=P(l,@"gate_value",&x),cv=P(l,@"ple_conv",&x),ad=P(l,@"add2",&x);id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];ENC(ce,q8,&l->key_proj,l->emb,l->key,10240,2560);ENC(ce,q8,&l->value_proj,l->emb,l->val,2560,2560);[ce setComputePipelineState:gn];[ce setBuffer:l->key offset:0 atIndex:0];[ce setBuffer:l->norm_key.buffer offset:0 atIndex:1];[ce setBuffer:l->key offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gn];[ce setBuffer:l->query offset:0 atIndex:0];[ce setBuffer:l->norm_query.buffer offset:0 atIndex:1];[ce setBuffer:l->query offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gv];[ce setBuffer:l->key offset:0 atIndex:0];[ce setBuffer:l->query offset:0 atIndex:1];[ce setBuffer:l->val offset:0 atIndex:2];[ce setBuffer:l->gated offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:gn];[ce setBuffer:l->gated offset:0 atIndex:0];[ce setBuffer:l->norm_conv.buffer offset:0 atIndex:1];[ce setBuffer:l->convnorm offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:cv];[ce setBuffer:l->convnorm offset:0 atIndex:0];[ce setBuffer:l->conv_weight.buffer offset:0 atIndex:1];[ce setBuffer:l->convstate offset:0 atIndex:2];[ce setBuffer:l->convout offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:ad];[ce setBuffer:l->gated offset:0 atIndex:0];[ce setBuffer:l->convout offset:0 atIndex:1];[ce setBuffer:l->out offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){E(e,n,cb.error.description.UTF8String);return -1;}if(getenv("QN_PLE_DEBUG")){const char*nn[]={"embed","key","value","query","gated","conv_norm","out"};id<MTLBuffer>bb[]={l->emb,l->key,l->val,l->query,l->gated,l->convnorm,l->out};size_t cc[]={2560,10240,2560,10240,10240,10240,10240};for(int z=0;z<7;z++){char pp[256];snprintf(pp,sizeof(pp),"/tmp/qn_ple_full/%s.bin",nn[z]);FILE*f=fopen(pp,"rb");if(f){float*r=malloc(cc[z]*4);fread(r,4,cc[z],f);fclose(f);float*a=bb[z].contents;double mx=0,ma=0;for(size_t j=0;j<cc[z];j++){double d=fabs((double)a[j]-r[j]);if(d>mx)mx=d;ma+=d;}fprintf(stderr,"DBG %s max=%g mae=%g first=%g ref=%g\n",nn[z],mx,ma/cc[z],a[0],r[0]);free(r);}}}memcpy(out->ple_output,l->out.contents,40960);memcpy(in->conv_state,l->convstate.contents,10240*9*4);out->elapsed_ms=nowms()-t0;}return 0;}
void qn_ple_layer_close(qn_ple_layer*l){if(!l)return;@autoreleasepool{l->pipes=nil;l->lib=nil;l->queue=nil;l->dev=nil;}for(uint32_t i=0;i<l->map_count;i++)qn_file_map_close(&l->maps[i]);qn_file_map_close(&l->ngram);qn_manifest_close(l->manifest);free(l);}
