#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "qn_qwen4_layer.h"
#include "qn_runtime.h"
#include <mach/mach_time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

struct qn_qwen4_layer {
    uint32_t layer_index;
    qn_file_map shard8, shard9, shard10;
    __strong id<MTLDevice> device;
    __strong id<MTLCommandQueue> queue;
    __strong id<MTLLibrary> library;
    __strong NSMutableDictionary<NSString*, id<MTLComputePipelineState>> *pipelines;
    __strong NSMutableDictionary<NSString*, id<MTLBuffer>> *scratch;
    qn_affine_metal_view expert_gate[512];
    qn_affine_metal_view expert_up[512];
    qn_affine_metal_view expert_down[512];
    uint8_t expert_cached[512];
    qn_affine_metal_view router_view;
    qn_affine_metal_view shared_gate_proj;
    qn_affine_metal_view shared_up_proj;
    qn_affine_metal_view shared_down_proj;
    qn_bf16_metal_view shared_gate_weight;
    qn_bf16_metal_view attn_hc_norm, attn_inject_weight, index_q_norm, index_k_norm, q_norm, k_norm;
    qn_affine_metal_view attn_mix_down, attn_mix_up, index_proj, q_proj, k_proj, v_proj, o_proj;
    qn_bf16_metal_view mlp_hc_norm, mlp_inject_weight;
    qn_affine_metal_view mlp_mix_down, mlp_mix_up;
    uint64_t expert_gate_w0, expert_gate_s0, expert_gate_b0;
    uint64_t expert_up_w0, expert_up_s0, expert_up_b0;
    uint64_t expert_down_w0, expert_down_s0, expert_down_b0;
};

static void seterr(char *e,size_t n,const char *s){if(e&&n)snprintf(e,n,"%s",s?s:"unknown error");}
static double now_ms(void){static mach_timebase_info_data_t tb;if(!tb.denom)mach_timebase_info(&tb);return (double)mach_absolute_time()*tb.numer/tb.denom/1e6;}

static NSString *kernel_source(void){return @R"METAL(
#include <metal_stdlib>
using namespace metal;
inline float bf16f(ushort v){return as_type<float>((uint)v<<16);} 
inline float sigm(float x){return 1.0f/(1.0f+exp(-x));}

kernel void q8_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/4;float a=0;
 for(uint g=0;g<G;g++){float s=bf16f(sc[r*G+g]),b=bf16f(bi[r*G+g]);for(uint j=lane;j<16;j+=32){uint p=w[r*W+g*16+j],k=g*64+j*4;float4 q=float4(p&255u,(p>>8)&255u,(p>>16)&255u,(p>>24)&255u);a+=dot(float4(x[k],x[k+1],x[k+2],x[k+3]),q*s+b);}}
 a=simd_sum(a);if(lane==0)y[r]=a;
}
kernel void q4_mv(device const uint*w[[buffer(0)]],device const ushort*sc[[buffer(1)]],device const ushort*bi[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&O[[buffer(5)]],constant uint&I[[buffer(6)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint r=tid/32;if(r>=O)return;uint G=I/64,W=I/8;float a=0;
 for(uint g=0;g<G;g++){float s=bf16f(sc[r*G+g]),b=bf16f(bi[r*G+g]);for(uint j=lane;j<8;j+=32){uint p=w[r*W+g*8+j],k=g*64+j*8;for(uint t=0;t<8;t++)a+=x[k+t]*((float)((p>>(4*t))&15u)*s+b);}}
 a=simd_sum(a);if(lane==0)y[r]=a;
}
kernel void silu_mul(device const float*g[[buffer(0)]],device const float*u[[buffer(1)]],device float*h[[buffer(2)]],constant uint&N[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<N){float z=g[i];h[i]=(z*sigm(z))*u[i];}}
kernel void zero_f32(device float*x[[buffer(0)]],constant uint&N[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<N)x[i]=0;}
kernel void scale_add(device const float*x[[buffer(0)]],device float*y[[buffer(1)]],constant float&w[[buffer(2)]],constant uint&N[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<N)y[i]+=x[i]*w;}
kernel void bf16_dot_sigmoid(device const ushort*w[[buffer(0)]],device const float*x[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){float a=0;for(uint j=lane;j<2560;j+=32)a+=bf16f(w[j])*x[j];a=simd_sum(a);if(lane==0)y[0]=sigm(a);}
kernel void mul_scalar(device float*x[[buffer(0)]],device const float*s[[buffer(1)]],constant uint&N[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<N)x[i]*=s[0];}

kernel void group_rms4(device const float*x[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint g=tid/32;if(g>=4)return;float ss=0;for(uint j=lane;j<2560;j+=32){float z=x[g*2560+j];ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/2560.0f+1e-6f);for(uint j=lane;j<2560;j+=32)y[g*2560+j]=x[g*2560+j]*inv*bf16f(w[g*2560+j]);}
kernel void silu_div4(device float*x[[buffer(0)]],constant uint&n[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<n){float z=x[i]*0.25f;x[i]=z*sigm(z);}}
kernel void sigmoid_ip(device float*x[[buffer(0)]],constant uint&n[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<n)x[i]=sigm(x[i]);}
kernel void mix4(device const float*xnorm[[buffer(0)]],device const float*mixw[[buffer(1)]],device float*out[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<2560){float z=0;for(uint g=0;g<4;g++)z+=xnorm[g*2560+i]*mixw[g*2560+i];out[i]=z*0.25f;}}
kernel void bf16_mv4(device const ushort*w[[buffer(0)]],device const float*x[[buffer(1)]],device float*y[[buffer(2)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint row=tid/32;if(row>=4)return;float a=0;for(uint j=lane;j<10240;j+=32)a+=bf16f(w[row*10240+j])*x[j];a=simd_sum(a);if(lane==0)y[row]=2.0f*sigm(a*0.25f);}
inline float rinv(uint j){return pow(10000000.0f,-(2.0f*(float)j)/64.0f);}
kernel void q_last_norm_rope(device const float*raw[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*out[[buffer(2)]],constant uint&tok[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=4)return;device const float*q=raw+h*128;threadgroup float tmp[128];float ss=0;for(uint j=lane;j<128;j+=32){float z=q[j];tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/128.0f+1e-6f);for(uint j=lane;j<128;j+=32)tmp[j]=tmp[j]*inv*bf16f(w[j]);threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)tok*rinv(j),c=cos(ang),sn=sin(ang);tmp[j]=a*c-b*sn;tmp[32+j]=b*c+a*sn;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)out[h*128+j]=tmp[j];}
kernel void copy_index_key(device const float*idxraw[[buffer(0)]],device float*dst[[buffer(1)]],constant uint&token_index[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<128)dst[token_index*128+i]=idxraw[512+i];}
kernel void kcomp_rope(device const float*raw[[buffer(0)]],device const ushort*w[[buffer(1)]],device float*out[[buffer(2)]],constant uint&blocks[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint block=tid/32;if(block>=blocks)return;threadgroup float tmp[128];float ss=0;for(uint j=lane;j<128;j+=32){float z=0;for(uint t=0;t<4;t++)z+=raw[(block*4+t)*128+j];z*=0.25f;tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/128.0f+1e-6f);for(uint j=lane;j<128;j+=32)tmp[j]=tmp[j]*inv*bf16f(w[j]);threadgroup_barrier(mem_flags::mem_threadgroup);uint pos=block*4;for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)pos*rinv(j),c=cos(ang),sn=sin(ang);tmp[j]=a*c-b*sn;tmp[32+j]=b*c+a*sn;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<128;j+=32)out[block*128+j]=tmp[j];}
kernel void score_blocks(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device float*scores[[buffer(2)]],constant uint&blocks[[buffer(3)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint b=tid/32;if(b>=blocks)return;float total=0;for(uint h=0;h<4;h++){float z=0;for(uint j=lane;j<128;j+=32)z+=q[h*128+j]*k[b*128+j];z=simd_sum(z);if(lane==0)total+=max(z,0.0f);}if(lane==0)scores[b]=total*0.08838834764831845f;}
kernel void gated_qkv(device const float*qraw[[buffer(0)]],device const float*kraw[[buffer(1)]],device const float*vraw[[buffer(2)]],device const ushort*qw[[buffer(3)]],device const ushort*kw[[buffer(4)]],device float*qout[[buffer(5)]],device float*gate[[buffer(6)]],device float*kout[[buffer(7)]],device float*vout[[buffer(8)]],constant uint&pos[[buffer(9)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h<24){threadgroup float tmp[256];float ss=0;for(uint j=lane;j<256;j+=32){float z=qraw[h*512+j];tmp[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/256.0f+1e-6f);for(uint j=lane;j<256;j+=32){tmp[j]=tmp[j]*inv*bf16f(qw[j]);gate[h*256+j]=qraw[h*512+256+j];}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmp[j],b=tmp[32+j],ang=(float)pos*rinv(j),c=cos(ang),sn=sin(ang);tmp[j]=a*c-b*sn;tmp[32+j]=b*c+a*sn;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<256;j+=32)qout[h*256+j]=tmp[j];}else if(h<26){uint kh=h-24;threadgroup float tmpk[256];float ss=0;for(uint j=lane;j<256;j+=32){float z=kraw[kh*256+j];tmpk[j]=z;ss+=z*z;}ss=simd_sum(ss);float inv=rsqrt(ss/256.0f+1e-6f);for(uint j=lane;j<256;j+=32){tmpk[j]=tmpk[j]*inv*bf16f(kw[j]);vout[kh*256+j]=vraw[kh*256+j];}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<32;j+=32){float a=tmpk[j],b=tmpk[32+j],ang=(float)pos*rinv(j),c=cos(ang),sn=sin(ang);tmpk[j]=a*c-b*sn;tmpk[32+j]=b*c+a*sn;}threadgroup_barrier(mem_flags::mem_threadgroup);for(uint j=lane;j<256;j+=32)kout[kh*256+j]=tmpk[j];}}
kernel void topk_blocks_bitonic(device const float*scores[[buffer(0)]],device int*token_ids[[buffer(1)]],constant uint&blocks[[buffer(2)]],constant uint&top[[buffer(3)]],constant uint&tail[[buffer(4)]],uint tid[[thread_index_in_threadgroup]]){
 threadgroup float sv[1024];threadgroup uint iv[1024];for(uint i=tid;i<1024;i+=256){if(i<blocks){sv[i]=scores[i];iv[i]=i;}else{sv[i]=-INFINITY;iv[i]=i;}}threadgroup_barrier(mem_flags::mem_threadgroup);
 for(uint k=2;k<=1024;k<<=1){for(uint j=k>>1;j>0;j>>=1){for(uint i=tid;i<1024;i+=256){uint ix=i^j;if(ix>i){bool up=((i&k)==0);float a=sv[i],b=sv[ix];if((a>b)==up){sv[i]=b;sv[ix]=a;uint ia=iv[i];iv[i]=iv[ix];iv[ix]=ia;}}}threadgroup_barrier(mem_flags::mem_threadgroup);}}
 for(uint r=tid;r<top;r+=256){uint b=iv[1023-r];uint o=r*4;token_ids[o]=(int)(b*4);token_ids[o+1]=(int)(b*4+1);token_ids[o+2]=(int)(b*4+2);token_ids[o+3]=(int)(b*4+3);}for(uint t=tid;t<tail;t+=256)token_ids[top*4+t]=(int)(blocks*4+t);
}
kernel void sparse_attn_scores_grouped(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device const int*ids[[buffer(2)]],device float*scores[[buffer(3)]],constant uint&nsel[[buffer(4)]],uint3 tg[[threadgroup_position_in_grid]],uint sg[[simdgroup_index_in_threadgroup]],uint lane[[thread_index_in_simdgroup]]){
 uint h=tg.y,t=tg.x*8+sg;if(h>=24||t>=nsel)return;uint kvh=h/12;int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)*(1.0f/16.0f);if(lane==0)scores[h*nsel+t]=z;
}
kernel void sparse_attn_scores_parallel(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device const int*ids[[buffer(2)]],device float*scores[[buffer(3)]],constant uint&nsel[[buffer(4)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint gi=tid/32,h=gi/nsel,t=gi-h*nsel;if(h>=24||t>=nsel)return;uint kvh=h/12;int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)*(1.0f/16.0f);if(lane==0)scores[h*nsel+t]=z;
}
kernel void sparse_attn_softmax(device float*scores[[buffer(0)]],constant uint&nsel[[buffer(1)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint h=tid/32;if(h>=24)return;device float*s=scores+h*nsel;float m=-INFINITY;for(uint t=lane;t<nsel;t+=32)m=max(m,s[t]);m=simd_max(m);float d=0;for(uint t=lane;t<nsel;t+=32)d+=exp(s[t]-m);d=simd_sum(d);for(uint t=lane;t<nsel;t+=32)s[t]=exp(s[t]-m)/d;
}
kernel void sparse_attn_value_parallel(device const float*probs[[buffer(0)]],device const float*v[[buffer(1)]],device const int*ids[[buffer(2)]],device float*out[[buffer(3)]],constant uint&nsel[[buffer(4)]],uint i[[thread_position_in_grid]]){
 if(i>=6144)return;uint h=i/256,j=i-h*256,kvh=h/12;float a=0;device const float*p=probs+h*nsel;for(uint t=0;t<nsel;t++){int id=ids[t];a+=p[t]*v[((uint)id*2+kvh)*256+j];}out[i]=a;
}
kernel void sparse_attn_probs(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device const int*ids[[buffer(2)]],device float*probs[[buffer(3)]],device float*denoms[[buffer(4)]],constant uint&nsel[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint h=tid/32;if(h>=24)return;uint kvh=h/12;float maxs=-INFINITY;
 for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)*(1.0f/16.0f);if(lane==0)maxs=max(maxs,z);}maxs=simd_broadcast_first(maxs);
 float den=0;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)*(1.0f/16.0f);if(lane==0){float p=exp(z-maxs);probs[h*nsel+t]=p;den+=p;}}if(lane==0)denoms[h]=den;
}
kernel void sparse_attn_value(device const float*probs[[buffer(0)]],device const float*denoms[[buffer(1)]],device const float*v[[buffer(2)]],device const int*ids[[buffer(3)]],device float*out[[buffer(4)]],constant uint&nsel[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){
 uint h=tid/32;if(h>=24)return;uint kvh=h/12;float invden=1.0f/denoms[h];for(uint j=lane;j<256;j+=32){float acc=0;for(uint t=0;t<nsel;t++){int id=ids[t];acc+=probs[h*nsel+t]*invden*v[((uint)id*2+kvh)*256+j];}out[h*256+j]=acc;}
}
kernel void sparse_gqa(device const float*q[[buffer(0)]],device const float*k[[buffer(1)]],device const float*v[[buffer(2)]],device const int*ids[[buffer(3)]],device float*out[[buffer(4)]],constant uint&nsel[[buffer(5)]],uint tid[[thread_position_in_grid]],uint lane[[thread_index_in_simdgroup]]){uint h=tid/32;if(h>=24)return;uint kvh=h/12;float maxs=-INFINITY;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)maxs=max(maxs,z);}maxs=simd_broadcast_first(maxs);float den=0;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint j=lane;j<256;j+=32)z+=q[h*256+j]*k[((uint)id*2+kvh)*256+j];z=simd_sum(z)/16.0f;if(lane==0)den+=exp(z-maxs);}den=simd_broadcast_first(den);for(uint j=lane;j<256;j+=32){float acc=0;for(uint t=0;t<nsel;t++){int id=ids[t];float z=0;for(uint d=0;d<256;d++)z+=q[h*256+d]*k[((uint)id*2+kvh)*256+d];float pr=exp(z/16.0f-maxs)/den;acc+=pr*v[((uint)id*2+kvh)*256+j];}out[h*256+j]=acc;}}
kernel void append_current_kv(device const float*kcur[[buffer(0)]],device const float*vcur[[buffer(1)]],device float*allk[[buffer(2)]],device float*allv[[buffer(3)]],constant uint&pos[[buffer(4)]],uint i[[thread_position_in_grid]]){if(i<512){allk[pos*512+i]=kcur[i];allv[pos*512+i]=vcur[i];}}
kernel void gate_apply(device float*x[[buffer(0)]],device const float*g[[buffer(1)]],uint i[[thread_position_in_grid]]){if(i<6144)x[i]*=sigm(g[i]);}
kernel void residual_inject(device const float*base[[buffer(0)]],device const float*attn[[buffer(1)]],device const float*inj[[buffer(2)]],device float*out[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<10240){uint g=i/2560,j=i%2560;out[i]=base[i]+attn[j]*inj[g];}}

)METAL";}

static id<MTLComputePipelineState> pipeline_for(qn_qwen4_layer *l, NSString *name, NSError **err){
    id<MTLComputePipelineState> p=l->pipelines[name]; if(p)return p;
    id<MTLFunction> f=[l->library newFunctionWithName:name]; if(!f)return nil;
    p=[l->device newComputePipelineStateWithFunction:f error:err]; if(p)l->pipelines[name]=p; return p;
}
static id<MTLBuffer> scratch(qn_qwen4_layer *l,NSString *name,NSUInteger bytes){
    id<MTLBuffer>b=l->scratch[name]; if(!b || b.length<bytes){b=[l->device newBufferWithLength:bytes options:MTLResourceStorageModeShared]; if(b)l->scratch[name]=b;} return b;
}

static NSDictionary *qn_load_manifest(const char *path,char *err,size_t errlen){
 @autoreleasepool{NSString*p=[NSString stringWithUTF8String:path];NSData*d=[NSData dataWithContentsOfFile:p];if(!d){seterr(err,errlen,"cannot read manifest");return nil;}NSError*e=nil;id obj=[NSJSONSerialization JSONObjectWithData:d options:0 error:&e];if(![obj isKindOfClass:[NSDictionary class]]){seterr(err,errlen,e?e.description.UTF8String:"invalid manifest");return nil;}NSDictionary*t=((NSDictionary*)obj)[@"tensors"];if(![t isKindOfClass:[NSDictionary class]]){seterr(err,errlen,"manifest tensors missing");return nil;}return t;}
}
static NSDictionary *qn_meta(NSDictionary*t,uint32_t layer,const char*suffix,char*err,size_t errlen){
 NSString*k=[NSString stringWithFormat:@"language_model.model.layers.%u.%s",layer,suffix];NSDictionary*m=t[k];if(![m isKindOfClass:[NSDictionary class]]){char b[512];snprintf(b,sizeof(b),"missing tensor %s",k.UTF8String);seterr(err,errlen,b);return nil;}return m;
}
static uint64_t qn_off(NSDictionary*m){return [m[@"file_offset"] unsignedLongLongValue];}
static NSString *qn_shard(NSDictionary*m){return m[@"shard"];}
static int qn_affine_manifest(NSDictionary*t,uint32_t layer,const char*base,uint32_t O,uint32_t I,uint32_t bits,qn_affine_desc*out,char*err,size_t errlen){
 char w[256],sc[256],bi[256];snprintf(w,sizeof(w),"%s.weight",base);snprintf(sc,sizeof(sc),"%s.scales",base);snprintf(bi,sizeof(bi),"%s.biases",base);NSDictionary*mw=qn_meta(t,layer,w,err,errlen),*ms=qn_meta(t,layer,sc,err,errlen),*mb=qn_meta(t,layer,bi,err,errlen);if(!mw||!ms||!mb)return -1;if(![qn_shard(mw) isEqualToString:qn_shard(ms)]||![qn_shard(mw) isEqualToString:qn_shard(mb)]){seterr(err,errlen,"affine tensor split across shards");return -1;}*out=(qn_affine_desc){qn_off(mw),qn_off(ms),qn_off(mb),O,I,64,bits};return 0;
}
static int qn_open_role_shards(qn_qwen4_layer*l,const qn_qwen4_layer_config*c,NSDictionary*t,char*err,size_t errlen){
 NSDictionary*ma=qn_meta(t,c->layer_index,"attn_hyper_connection.hc_norm.weight",err,errlen),*mb=qn_meta(t,c->layer_index,"mlp.switch_mlp.gate_proj.weight",err,errlen),*mc=qn_meta(t,c->layer_index,"self_attn.q_proj.weight",err,errlen);if(!ma||!mb||!mc)return -1;NSString*A=qn_shard(ma),*B=qn_shard(mb),*C=qn_shard(mc);if(!A||!B||!C||[A isEqualToString:B]||[A isEqualToString:C]||[B isEqualToString:C]){seterr(err,errlen,"unexpected QSA shard roles");return -1;}NSString*dir=[NSString stringWithUTF8String:c->model_dir];NSString*pa=[dir stringByAppendingPathComponent:A],*pb=[dir stringByAppendingPathComponent:B],*pc=[dir stringByAppendingPathComponent:C];if(qn_file_map_open(&l->shard8,pa.UTF8String,err,errlen)||qn_file_map_open(&l->shard9,pb.UTF8String,err,errlen)||qn_file_map_open(&l->shard10,pc.UTF8String,err,errlen))return -1;return 0;
}

int qn_qwen4_layer_open(qn_qwen4_layer **out,const qn_qwen4_layer_config *c,char *err,size_t errlen){
 if(!out||!c){seterr(err,errlen,"invalid layer config");return -1;}
 BOOL manifest_mode=(c->model_dir&&c->manifest_path);
 if(!manifest_mode && (!c->shard8_path||!c->shard9_path||!c->shard10_path)){seterr(err,errlen,"legacy config needs three shard paths");return -1;}
 if(!manifest_mode && c->layer_index!=11){seterr(err,errlen,"non-L11 layers require model_dir + manifest_path");return -1;}
 qn_qwen4_layer*l=calloc(1,sizeof(*l));if(!l){seterr(err,errlen,"calloc failed");return -1;}l->shard8.fd=l->shard9.fd=l->shard10.fd=-1;l->layer_index=c->layer_index;
 @autoreleasepool{
  NSDictionary*t=nil;if(manifest_mode){t=qn_load_manifest(c->manifest_path,err,errlen);if(!t||qn_open_role_shards(l,c,t,err,errlen)){qn_qwen4_layer_close(l);return -1;}}else if(qn_file_map_open(&l->shard8,c->shard8_path,err,errlen)||qn_file_map_open(&l->shard9,c->shard9_path,err,errlen)||qn_file_map_open(&l->shard10,c->shard10_path,err,errlen)){qn_qwen4_layer_close(l);return -1;}
  l->device=MTLCreateSystemDefaultDevice();if(!l->device){seterr(err,errlen,"no Metal device");qn_qwen4_layer_close(l);return -1;}l->queue=[l->device newCommandQueue];NSError*e=nil;l->library=[l->device newLibraryWithSource:kernel_source() options:nil error:&e];if(!l->library){seterr(err,errlen,e.description.UTF8String);qn_qwen4_layer_close(l);return -1;}l->pipelines=[NSMutableDictionary dictionary];l->scratch=[NSMutableDictionary dictionary];
  for(NSString*n in @[@"q8_mv",@"q4_mv",@"silu_mul",@"zero_f32",@"scale_add",@"bf16_dot_sigmoid",@"mul_scalar",@"group_rms4",@"silu_div4",@"sigmoid_ip",@"mix4",@"bf16_mv4",@"q_last_norm_rope",@"copy_index_key",@"kcomp_rope",@"score_blocks",@"topk_blocks_bitonic",@"gated_qkv",@"sparse_gqa",@"sparse_attn_probs",@"sparse_attn_value",@"sparse_attn_scores_parallel",@"sparse_attn_scores_grouped",@"sparse_attn_softmax",@"sparse_attn_value_parallel",@"append_current_kv",@"gate_apply",@"residual_inject"]){if(!pipeline_for(l,n,&e)){seterr(err,errlen,e.description.UTF8String);qn_qwen4_layer_close(l);return -1;}}
  scratch(l,@"router_logits",512*4);scratch(l,@"expert_gate",640*4);scratch(l,@"expert_up",640*4);scratch(l,@"expert_hidden",640*4);scratch(l,@"expert_down",2560*4);scratch(l,@"routed",2560*4);scratch(l,@"shared",2560*4);scratch(l,@"moe_total",2560*4);scratch(l,@"shared_gate",4);
  qn_affine_desc rad,sgd,sud,sdd,ahd,ahu,idx,qd,kd,vd,od,mhd,mhu;
  uint64_t ahcn,aiw,iqn,ikn,qn,kn,sgw,mhcn,miw;
  if(manifest_mode){
#define AFF(dst,base,O,I,bits) if(qn_affine_manifest(t,c->layer_index,base,O,I,bits,&dst,err,errlen)){qn_qwen4_layer_close(l);return -1;}
   AFF(rad,"mlp.gate",512,2560,8);AFF(sgd,"mlp.shared_expert.gate_proj",640,2560,8);AFF(sud,"mlp.shared_expert.up_proj",640,2560,8);AFF(sdd,"mlp.shared_expert.down_proj",2560,640,8);
   AFF(ahd,"attn_hyper_connection.input_mix_weight_down",320,10240,8);AFF(ahu,"attn_hyper_connection.input_mix_weight_up",10240,320,8);AFF(idx,"self_attn.indexer.index_qk_proj",640,2560,8);AFF(qd,"self_attn.q_proj",12288,2560,8);AFF(kd,"self_attn.k_proj",512,2560,8);AFF(vd,"self_attn.v_proj",512,2560,8);AFF(od,"self_attn.o_proj",2560,6144,8);AFF(mhd,"mlp_hyper_connection.input_mix_weight_down",320,10240,8);AFF(mhu,"mlp_hyper_connection.input_mix_weight_up",10240,320,8);
#undef AFF
#define OFF(dst,name) do{NSDictionary*m=qn_meta(t,c->layer_index,name,err,errlen);if(!m){qn_qwen4_layer_close(l);return -1;}dst=qn_off(m);}while(0)
   OFF(ahcn,"attn_hyper_connection.hc_norm.weight");OFF(aiw,"attn_hyper_connection.block_inject_weight.weight");OFF(iqn,"self_attn.indexer.q_layernorm.weight");OFF(ikn,"self_attn.indexer.k_layernorm.weight");OFF(qn,"self_attn.q_norm.weight");OFF(kn,"self_attn.k_norm.weight");OFF(sgw,"mlp.shared_expert_gate.weight");OFF(mhcn,"mlp_hyper_connection.hc_norm.weight");OFF(miw,"mlp_hyper_connection.block_inject_weight.weight");
   NSDictionary*egw=qn_meta(t,c->layer_index,"mlp.switch_mlp.gate_proj.weight",err,errlen),*egs=qn_meta(t,c->layer_index,"mlp.switch_mlp.gate_proj.scales",err,errlen),*egb=qn_meta(t,c->layer_index,"mlp.switch_mlp.gate_proj.biases",err,errlen),*euw=qn_meta(t,c->layer_index,"mlp.switch_mlp.up_proj.weight",err,errlen),*eus=qn_meta(t,c->layer_index,"mlp.switch_mlp.up_proj.scales",err,errlen),*eub=qn_meta(t,c->layer_index,"mlp.switch_mlp.up_proj.biases",err,errlen),*edw=qn_meta(t,c->layer_index,"mlp.switch_mlp.down_proj.weight",err,errlen),*eds=qn_meta(t,c->layer_index,"mlp.switch_mlp.down_proj.scales",err,errlen),*edb=qn_meta(t,c->layer_index,"mlp.switch_mlp.down_proj.biases",err,errlen);if(!egw||!egs||!egb||!euw||!eus||!eub||!edw||!eds||!edb){qn_qwen4_layer_close(l);return -1;}
   l->expert_gate_w0=qn_off(egw);l->expert_gate_s0=qn_off(egs);l->expert_gate_b0=qn_off(egb);l->expert_up_w0=qn_off(euw);l->expert_up_s0=qn_off(eus);l->expert_up_b0=qn_off(eub);l->expert_down_w0=qn_off(edw);l->expert_down_s0=qn_off(eds);l->expert_down_b0=qn_off(edb);
#undef OFF
  }else{
   rad=(qn_affine_desc){471869896,473180616,473221576,512,2560,64,8};sgd=(qn_affine_desc){475003336,476641736,476692936,640,2560,64,8};sud=(qn_affine_desc){476744136,478382536,478433736,640,2560,64,8};sdd=(qn_affine_desc){473262536,474900936,474952136,2560,640,64,8};ahd=(qn_affine_desc){485652256,488929056,489031456,320,10240,64,8};ahu=(qn_affine_desc){489133856,492410656,492513056,10240,320,64,8};idx=(qn_affine_desc){485555656,487194056,487245256,640,2560,64,8};qd=(qn_affine_desc){505402312,536859592,537842632,12288,2560,64,8};kd=(qn_affine_desc){487297480,488608200,488649160,512,2560,64,8};vd=(qn_affine_desc){538825672,540136392,540177352,512,2560,64,8};od=(qn_affine_desc){488690120,504418760,504910280,2560,6144,64,8};mhd=(qn_affine_desc){478592456,481869256,481971656,320,10240,64,8};mhu=(qn_affine_desc){482074056,485350856,485453256,10240,320,64,8};ahcn=485631776;aiw=485549856;iqn=487296712;ikn=487296456;qn=505401800;kn=487296968;sgw=478484936;mhcn=478571976;miw=478490056;l->expert_gate_w0=896;l->expert_gate_s0=419431296;l->expert_gate_b0=445645696;l->expert_up_w0=471860096;l->expert_up_s0=891290496;l->expert_up_b0=917504896;l->expert_down_w0=10696;l->expert_down_s0=419441096;l->expert_down_b0=445655496;
  }
  if(qn_affine_make_view(l->device,&l->shard10,&rad,&l->router_view,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&sgd,&l->shared_gate_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&sud,&l->shared_up_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&sdd,&l->shared_down_proj,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,sgw,2560,&l->shared_gate_weight,err,errlen)){qn_qwen4_layer_close(l);return -1;}
  if(qn_bf16_make_view(l->device,&l->shard8,ahcn,10240,&l->attn_hc_norm,err,errlen)||qn_bf16_make_view(l->device,&l->shard8,aiw,40960,&l->attn_inject_weight,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,iqn,128,&l->index_q_norm,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,ikn,128,&l->index_k_norm,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,qn,256,&l->q_norm,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,kn,256,&l->k_norm,err,errlen)||qn_affine_make_view(l->device,&l->shard8,&ahd,&l->attn_mix_down,err,errlen)||qn_affine_make_view(l->device,&l->shard8,&ahu,&l->attn_mix_up,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&idx,&l->index_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&qd,&l->q_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&kd,&l->k_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&vd,&l->v_proj,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&od,&l->o_proj,err,errlen)){qn_qwen4_layer_close(l);return -1;}
  if(qn_bf16_make_view(l->device,&l->shard10,mhcn,10240,&l->mlp_hc_norm,err,errlen)||qn_bf16_make_view(l->device,&l->shard10,miw,40960,&l->mlp_inject_weight,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&mhd,&l->mlp_mix_down,err,errlen)||qn_affine_make_view(l->device,&l->shard10,&mhu,&l->mlp_mix_up,err,errlen)){qn_qwen4_layer_close(l);return -1;}
 }
 *out=l;return 0;
}



static void encode_affine(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>ps,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I);
int qn_qwen4_layer_forward_attention(qn_qwen4_layer*l,const qn_qwen4_decode_input*in,float*hyper_output,double*elapsed_ms,char*err,size_t errlen){
 if(!l||!in||!in->hyper_state||!in->indexer_raw_history||!in->key_history||!in->value_history||!hyper_output){seterr(err,errlen,"invalid attention arguments");return -1;}uint32_t pos=in->position,T=pos+1,B=T/4,tail=T-B*4;if(B==0){seterr(err,errlen,"attention runtime expects at least one complete 4-token block");return -1;}uint32_t top=B<512?B:512,nsel=top*4+tail;
 @autoreleasepool{NSError*e=nil;
  id<MTLComputePipelineState>group=pipeline_for(l,@"group_rms4",&e),q8=pipeline_for(l,@"q8_mv",&e),sdiv=pipeline_for(l,@"silu_div4",&e),sig=pipeline_for(l,@"sigmoid_ip",&e),mix=pipeline_for(l,@"mix4",&e),injp=pipeline_for(l,@"bf16_mv4",&e),iqp=pipeline_for(l,@"q_last_norm_rope",&e),copyk=pipeline_for(l,@"copy_index_key",&e),kcp=pipeline_for(l,@"kcomp_rope",&e),scorep=pipeline_for(l,@"score_blocks",&e),topkp=pipeline_for(l,@"topk_blocks_bitonic",&e),gq=pipeline_for(l,@"gated_qkv",&e),attp=pipeline_for(l,@"sparse_gqa",&e),probp=pipeline_for(l,@"sparse_attn_probs",&e),valp=pipeline_for(l,@"sparse_attn_value",&e),scorepar=pipeline_for(l,@"sparse_attn_scores_parallel",&e),scoregrp=pipeline_for(l,@"sparse_attn_scores_grouped",&e),softp=pipeline_for(l,@"sparse_attn_softmax",&e),valpar=pipeline_for(l,@"sparse_attn_value_parallel",&e),appendkv=pipeline_for(l,@"append_current_kv",&e),gap=pipeline_for(l,@"gate_apply",&e),rip=pipeline_for(l,@"residual_inject",&e);if(!group||!q8||!sdiv||!sig||!mix||!injp||!iqp||!copyk||!kcp||!scorep||!topkp||!gq||!attp||!probp||!valp||!scorepar||!scoregrp||!softp||!valpar||!appendkv||!gap||!rip){seterr(err,errlen,e.description.UTF8String);return -1;}
  id<MTLBuffer>hb=scratch(l,@"att_hyper",10240*4),xnorm=scratch(l,@"att_xnorm",10240*4),lo=scratch(l,@"att_lo",320*4),mixw=scratch(l,@"att_mixw",10240*4),mixed=scratch(l,@"att_mixed",2560*4),inj=scratch(l,@"att_inj",4*4),idxraw=scratch(l,@"att_idxraw",640*4),iq=scratch(l,@"att_iq",512*4),blkraw=scratch(l,@"att_blkraw",(NSUInteger)B*4*128*4),ikblocks=scratch(l,@"att_ikblocks",(NSUInteger)B*128*4),scores=scratch(l,@"att_scores",(NSUInteger)B*4),qraw=scratch(l,@"att_qraw",12288*4),kraw=scratch(l,@"att_kraw",512*4),vraw=scratch(l,@"att_vraw",512*4),q=scratch(l,@"att_q",6144*4),gate=scratch(l,@"att_gate",6144*4),kcur=scratch(l,@"att_kcur",512*4),vcur=scratch(l,@"att_vcur",512*4),allk=scratch(l,@"att_allk",(NSUInteger)T*2*256*4),allv=scratch(l,@"att_allv",(NSUInteger)T*2*256*4),ids=scratch(l,@"att_ids",(NSUInteger)nsel*4),probs=scratch(l,@"att_probs",(NSUInteger)24*nsel*4),denoms=scratch(l,@"att_denoms",24*4),att=scratch(l,@"att_out6144",6144*4),out=scratch(l,@"att_out2560",2560*4),final=scratch(l,@"att_final",10240*4);
  memcpy(hb.contents,in->hyper_state,10240*4);uint32_t complete_tokens=B*4,hist_complete=complete_tokens<pos?complete_tokens:pos;if(hist_complete)memcpy(blkraw.contents,in->indexer_raw_history,(size_t)hist_complete*128*4);memcpy(allk.contents,in->key_history,(size_t)pos*2*256*4);memcpy(allv.contents,in->value_history,(size_t)pos*2*256*4);
  uint32_t n320=320,n10240=10240;double t0=now_ms();id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:group];[ce setBuffer:hb offset:0 atIndex:0];[ce setBuffer:l->attn_hc_norm.buffer offset:0 atIndex:1];[ce setBuffer:xnorm offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];encode_affine(ce,q8,&l->attn_mix_down,xnorm,lo,320,10240);[ce setComputePipelineState:sdiv];[ce setBuffer:lo offset:0 atIndex:0];[ce setBytes:&n320 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q8,&l->attn_mix_up,lo,mixw,10240,320);[ce setComputePipelineState:sig];[ce setBuffer:mixw offset:0 atIndex:0];[ce setBytes:&n10240 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:mix];[ce setBuffer:xnorm offset:0 atIndex:0];[ce setBuffer:mixw offset:0 atIndex:1];[ce setBuffer:mixed offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:injp];[ce setBuffer:l->attn_inject_weight.buffer offset:0 atIndex:0];[ce setBuffer:xnorm offset:0 atIndex:1];[ce setBuffer:inj offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];encode_affine(ce,q8,&l->index_proj,mixed,idxraw,640,2560);[ce setComputePipelineState:iqp];[ce setBuffer:idxraw offset:0 atIndex:0];[ce setBuffer:l->index_q_norm.buffer offset:0 atIndex:1];[ce setBuffer:iq offset:0 atIndex:2];[ce setBytes:&pos length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];if(tail==0){[ce setComputePipelineState:copyk];[ce setBuffer:idxraw offset:0 atIndex:0];[ce setBuffer:blkraw offset:0 atIndex:1];[ce setBytes:&pos length:4 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(128,1,1)];}[ce setComputePipelineState:kcp];[ce setBuffer:blkraw offset:0 atIndex:0];[ce setBuffer:l->index_k_norm.buffer offset:0 atIndex:1];[ce setBuffer:ikblocks offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:scorep];[ce setBuffer:iq offset:0 atIndex:0];[ce setBuffer:ikblocks offset:0 atIndex:1];[ce setBuffer:scores offset:0 atIndex:2];[ce setBytes:&B length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake((NSUInteger)B*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:topkp];[ce setBuffer:scores offset:0 atIndex:0];[ce setBuffer:ids offset:0 atIndex:1];[ce setBytes:&B length:4 atIndex:2];[ce setBytes:&top length:4 atIndex:3];[ce setBytes:&tail length:4 atIndex:4];[ce dispatchThreadgroups:MTLSizeMake(1,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];
  cb=[l->queue commandBuffer];ce=[cb computeCommandEncoder];encode_affine(ce,q8,&l->q_proj,mixed,qraw,12288,2560);encode_affine(ce,q8,&l->k_proj,mixed,kraw,512,2560);encode_affine(ce,q8,&l->v_proj,mixed,vraw,512,2560);[ce setComputePipelineState:gq];[ce setBuffer:qraw offset:0 atIndex:0];[ce setBuffer:kraw offset:0 atIndex:1];[ce setBuffer:vraw offset:0 atIndex:2];[ce setBuffer:l->q_norm.buffer offset:0 atIndex:3];[ce setBuffer:l->k_norm.buffer offset:0 atIndex:4];[ce setBuffer:q offset:0 atIndex:5];[ce setBuffer:gate offset:0 atIndex:6];[ce setBuffer:kcur offset:0 atIndex:7];[ce setBuffer:vcur offset:0 atIndex:8];[ce setBytes:&pos length:4 atIndex:9];[ce dispatchThreads:MTLSizeMake(26*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:appendkv];[ce setBuffer:kcur offset:0 atIndex:0];[ce setBuffer:vcur offset:0 atIndex:1];[ce setBuffer:allk offset:0 atIndex:2];[ce setBuffer:allv offset:0 atIndex:3];[ce setBytes:&pos length:4 atIndex:4];[ce dispatchThreads:MTLSizeMake(512,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:scoregrp];[ce setBuffer:q offset:0 atIndex:0];[ce setBuffer:allk offset:0 atIndex:1];[ce setBuffer:ids offset:0 atIndex:2];[ce setBuffer:probs offset:0 atIndex:3];[ce setBytes:&nsel length:4 atIndex:4];[ce dispatchThreadgroups:MTLSizeMake((nsel+7)/8,24,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:softp];[ce setBuffer:probs offset:0 atIndex:0];[ce setBytes:&nsel length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(24*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:valpar];[ce setBuffer:probs offset:0 atIndex:0];[ce setBuffer:allv offset:0 atIndex:1];[ce setBuffer:ids offset:0 atIndex:2];[ce setBuffer:att offset:0 atIndex:3];[ce setBytes:&nsel length:4 atIndex:4];[ce dispatchThreads:MTLSizeMake(6144,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:gap];[ce setBuffer:att offset:0 atIndex:0];[ce setBuffer:gate offset:0 atIndex:1];[ce dispatchThreads:MTLSizeMake(6144,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q8,&l->o_proj,att,out,2560,6144);[ce setComputePipelineState:rip];[ce setBuffer:hb offset:0 atIndex:0];[ce setBuffer:out offset:0 atIndex:1];[ce setBuffer:inj offset:0 atIndex:2];[ce setBuffer:final offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}double t3=now_ms();memcpy(hyper_output,final.contents,10240*4);if(elapsed_ms)*elapsed_ms=t3-t0;if(getenv("QN_PROFILE"))fprintf(stderr,"att_profile gpu_chain=%.4f\n",t3-t0);
 }
 return 0;
}

static void encode_affine(id<MTLComputeCommandEncoder>ce,id<MTLComputePipelineState>ps,qn_affine_metal_view*v,id<MTLBuffer>x,id<MTLBuffer>y,uint32_t O,uint32_t I){
 [ce setComputePipelineState:ps];[ce setBuffer:v->weight offset:0 atIndex:0];[ce setBuffer:v->scales offset:0 atIndex:1];[ce setBuffer:v->biases offset:0 atIndex:2];[ce setBuffer:x offset:0 atIndex:3];[ce setBuffer:y offset:0 atIndex:4];[ce setBytes:&O length:4 atIndex:5];[ce setBytes:&I length:4 atIndex:6];[ce dispatchThreads:MTLSizeMake((NSUInteger)O*32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
}
typedef struct{float p;uint32_t i;} qn_route_pair;
static int route_cmp(const void*a,const void*b){float x=((const qn_route_pair*)a)->p,y=((const qn_route_pair*)b)->p;return x<y?1:x>y?-1:0;}

int qn_qwen4_layer_forward_moe(qn_qwen4_layer*l,const float*hidden,float*output,uint32_t selected_ids[10],float selected_weights[10],double*elapsed_ms,char*err,size_t errlen){
 if(!l||!hidden||!output){seterr(err,errlen,"invalid moe arguments");return -1;}
 @autoreleasepool{
  NSError*e=nil;id<MTLComputePipelineState>q8=pipeline_for(l,@"q8_mv",&e),q4=pipeline_for(l,@"q4_mv",&e),sm=pipeline_for(l,@"silu_mul",&e),zp=pipeline_for(l,@"zero_f32",&e),sa=pipeline_for(l,@"scale_add",&e),bd=pipeline_for(l,@"bf16_dot_sigmoid",&e),ms=pipeline_for(l,@"mul_scalar",&e);
  if(!q8||!q4||!sm||!zp||!sa||!bd||!ms){seterr(err,errlen,e.description.UTF8String);return -1;}
  id<MTLBuffer>xb=scratch(l,@"moe_input",2560*4),logb=scratch(l,@"router_logits",512*4),gb=scratch(l,@"expert_gate",640*4),ub=scratch(l,@"expert_up",640*4),hb=scratch(l,@"expert_hidden",640*4),db=scratch(l,@"expert_down",2560*4),routed=scratch(l,@"routed",2560*4),shared=scratch(l,@"shared",2560*4),total=scratch(l,@"moe_total",2560*4),sgate=scratch(l,@"shared_gate",4);
  memcpy(xb.contents,hidden,2560*4);
  double t0=now_ms();id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];encode_affine(ce,q8,&l->router_view,xb,logb,512,2560);[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}
  float*lg=logb.contents,vmax=-INFINITY;for(uint32_t i=0;i<512;i++)if(lg[i]>vmax)vmax=lg[i];double den=0;for(uint32_t i=0;i<512;i++)den+=exp((double)lg[i]-vmax);qn_route_pair p[512];for(uint32_t i=0;i<512;i++){p[i].p=(float)(exp((double)lg[i]-vmax)/den);p[i].i=i;}qsort(p,512,sizeof(*p),route_cmp);for(uint32_t j=0;j<10;j++){if(selected_ids)selected_ids[j]=p[j].i;if(selected_weights)selected_weights[j]=p[j].p;}
  uint32_t N2560=2560,N640=640;cb=[l->queue commandBuffer];ce=[cb computeCommandEncoder];[ce setComputePipelineState:zp];[ce setBuffer:routed offset:0 atIndex:0];[ce setBytes:&N2560 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  for(uint32_t j=0;j<10;j++){uint64_t E=p[j].i,gw=E*(uint64_t)640*320*4,gs=E*(uint64_t)640*40*2,dw=E*(uint64_t)2560*80*4,ds=E*(uint64_t)2560*10*2;qn_affine_desc gd={l->expert_gate_w0+gw,l->expert_gate_s0+gs,l->expert_gate_b0+gs,640,2560,64,4},ud={l->expert_up_w0+gw,l->expert_up_s0+gs,l->expert_up_b0+gs,640,2560,64,4},dd={l->expert_down_w0+dw,l->expert_down_s0+ds,l->expert_down_b0+ds,2560,640,64,4};if(!l->expert_cached[E]){if(qn_affine_make_view(l->device,&l->shard9,&gd,&l->expert_gate[E],err,errlen)||qn_affine_make_view(l->device,&l->shard9,&ud,&l->expert_up[E],err,errlen)||qn_affine_make_view(l->device,&l->shard10,&dd,&l->expert_down[E],err,errlen))return -1;l->expert_cached[E]=1;}encode_affine(ce,q4,&l->expert_gate[E],xb,gb,640,2560);encode_affine(ce,q4,&l->expert_up[E],xb,ub,640,2560);[ce setComputePipelineState:sm];[ce setBuffer:gb offset:0 atIndex:0];[ce setBuffer:ub offset:0 atIndex:1];[ce setBuffer:hb offset:0 atIndex:2];[ce setBytes:&N640 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(640,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q4,&l->expert_down[E],hb,db,2560,640);float w=p[j].p;[ce setComputePipelineState:sa];[ce setBuffer:db offset:0 atIndex:0];[ce setBuffer:routed offset:0 atIndex:1];[ce setBytes:&w length:4 atIndex:2];[ce setBytes:&N2560 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];}
  encode_affine(ce,q8,&l->shared_gate_proj,xb,gb,640,2560);encode_affine(ce,q8,&l->shared_up_proj,xb,ub,640,2560);[ce setComputePipelineState:sm];[ce setBuffer:gb offset:0 atIndex:0];[ce setBuffer:ub offset:0 atIndex:1];[ce setBuffer:hb offset:0 atIndex:2];[ce setBytes:&N640 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(640,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q8,&l->shared_down_proj,hb,shared,2560,640);[ce setComputePipelineState:bd];[ce setBuffer:l->shared_gate_weight.buffer offset:0 atIndex:0];[ce setBuffer:xb offset:0 atIndex:1];[ce setBuffer:sgate offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:ms];[ce setBuffer:shared offset:0 atIndex:0];[ce setBuffer:sgate offset:0 atIndex:1];[ce setBytes:&N2560 length:4 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:sa];float one=1.0f;[ce setBuffer:shared offset:0 atIndex:0];[ce setBuffer:routed offset:0 atIndex:1];[ce setBytes:&one length:4 atIndex:2];[ce setBytes:&N2560 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}memcpy(output,routed.contents,2560*4);if(elapsed_ms)*elapsed_ms=now_ms()-t0;
 }
 return 0;
}


static int qn_run_mlp_hyper(qn_qwen4_layer*l,const float*hyper,float*mixed_out,float inj_out[4],double*elapsed,char*err,size_t errlen){
 @autoreleasepool{NSError*e=nil;id<MTLComputePipelineState>group=pipeline_for(l,@"group_rms4",&e),q8=pipeline_for(l,@"q8_mv",&e),sdiv=pipeline_for(l,@"silu_div4",&e),sig=pipeline_for(l,@"sigmoid_ip",&e),mix=pipeline_for(l,@"mix4",&e),injp=pipeline_for(l,@"bf16_mv4",&e);if(!group||!q8||!sdiv||!sig||!mix||!injp){seterr(err,errlen,e.description.UTF8String);return -1;}
  id<MTLBuffer>hb=scratch(l,@"mlph_hyper",10240*4),xn=scratch(l,@"mlph_xnorm",10240*4),lo=scratch(l,@"mlph_lo",320*4),mw=scratch(l,@"mlph_mixw",10240*4),mo=scratch(l,@"mlph_mixed",2560*4),io=scratch(l,@"mlph_inj",4*4);memcpy(hb.contents,hyper,10240*4);uint32_t n320=320,n10240=10240;double t0=now_ms();id<MTLCommandBuffer>cb=[l->queue commandBuffer];id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];[ce setComputePipelineState:group];[ce setBuffer:hb offset:0 atIndex:0];[ce setBuffer:l->mlp_hc_norm.buffer offset:0 atIndex:1];[ce setBuffer:xn offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];encode_affine(ce,q8,&l->mlp_mix_down,xn,lo,320,10240);[ce setComputePipelineState:sdiv];[ce setBuffer:lo offset:0 atIndex:0];[ce setBytes:&n320 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q8,&l->mlp_mix_up,lo,mw,10240,320);[ce setComputePipelineState:sig];[ce setBuffer:mw offset:0 atIndex:0];[ce setBytes:&n10240 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:mix];[ce setBuffer:xn offset:0 atIndex:0];[ce setBuffer:mw offset:0 atIndex:1];[ce setBuffer:mo offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce setComputePipelineState:injp];[ce setBuffer:l->mlp_inject_weight.buffer offset:0 atIndex:0];[ce setBuffer:xn offset:0 atIndex:1];[ce setBuffer:io offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}memcpy(mixed_out,mo.contents,2560*4);memcpy(inj_out,io.contents,4*4);if(elapsed)*elapsed=now_ms()-t0;}
 return 0;
}


static int qn_run_mlp_full(qn_qwen4_layer*l,const float*hyper,float*final_out,uint32_t selected_ids[10],float selected_weights[10],double*elapsed,char*err,size_t errlen){
 @autoreleasepool{
  NSError*e=nil; id<MTLComputePipelineState>group=pipeline_for(l,@"group_rms4",&e),q8=pipeline_for(l,@"q8_mv",&e),q4=pipeline_for(l,@"q4_mv",&e),sdiv=pipeline_for(l,@"silu_div4",&e),sig=pipeline_for(l,@"sigmoid_ip",&e),mix=pipeline_for(l,@"mix4",&e),injp=pipeline_for(l,@"bf16_mv4",&e),sm=pipeline_for(l,@"silu_mul",&e),zp=pipeline_for(l,@"zero_f32",&e),sa=pipeline_for(l,@"scale_add",&e),bd=pipeline_for(l,@"bf16_dot_sigmoid",&e),ms=pipeline_for(l,@"mul_scalar",&e),rip=pipeline_for(l,@"residual_inject",&e);
  if(!group||!q8||!q4||!sdiv||!sig||!mix||!injp||!sm||!zp||!sa||!bd||!ms||!rip){seterr(err,errlen,e.description.UTF8String);return -1;}
  id<MTLBuffer>base=scratch(l,@"mlpf_hyper",10240*4),xn=scratch(l,@"mlpf_xnorm",10240*4),lo=scratch(l,@"mlpf_lo",320*4),mw=scratch(l,@"mlpf_mixw",10240*4),mo=scratch(l,@"mlpf_mixed",2560*4),io=scratch(l,@"mlpf_inj",4*4),logb=scratch(l,@"router_logits",512*4),gb=scratch(l,@"expert_gate",640*4),ub=scratch(l,@"expert_up",640*4),eh=scratch(l,@"expert_hidden",640*4),db=scratch(l,@"expert_down",2560*4),routed=scratch(l,@"routed",2560*4),shared=scratch(l,@"shared",2560*4),sgate=scratch(l,@"shared_gate",4),finalb=scratch(l,@"mlpf_final",10240*4);
  memcpy(base.contents,hyper,10240*4); uint32_t n320=320,n10240=10240,N2560=2560,N640=640; double t0=now_ms();
  id<MTLCommandBuffer>cb=[l->queue commandBuffer]; id<MTLComputeCommandEncoder>ce=[cb computeCommandEncoder];
  [ce setComputePipelineState:group];[ce setBuffer:base offset:0 atIndex:0];[ce setBuffer:l->mlp_hc_norm.buffer offset:0 atIndex:1];[ce setBuffer:xn offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  encode_affine(ce,q8,&l->mlp_mix_down,xn,lo,320,10240);[ce setComputePipelineState:sdiv];[ce setBuffer:lo offset:0 atIndex:0];[ce setBytes:&n320 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(320,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  encode_affine(ce,q8,&l->mlp_mix_up,lo,mw,10240,320);[ce setComputePipelineState:sig];[ce setBuffer:mw offset:0 atIndex:0];[ce setBytes:&n10240 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  [ce setComputePipelineState:mix];[ce setBuffer:xn offset:0 atIndex:0];[ce setBuffer:mw offset:0 atIndex:1];[ce setBuffer:mo offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  [ce setComputePipelineState:injp];[ce setBuffer:l->mlp_inject_weight.buffer offset:0 atIndex:0];[ce setBuffer:xn offset:0 atIndex:1];[ce setBuffer:io offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(128,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];
  encode_affine(ce,q8,&l->router_view,mo,logb,512,2560);[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}
  float*lg=logb.contents,vmax=-INFINITY;for(uint32_t i=0;i<512;i++)if(lg[i]>vmax)vmax=lg[i];double den=0;for(uint32_t i=0;i<512;i++)den+=exp((double)lg[i]-vmax);qn_route_pair rp[512];for(uint32_t i=0;i<512;i++){rp[i].p=(float)(exp((double)lg[i]-vmax)/den);rp[i].i=i;}qsort(rp,512,sizeof(*rp),route_cmp);for(uint32_t j=0;j<10;j++){if(selected_ids)selected_ids[j]=rp[j].i;if(selected_weights)selected_weights[j]=rp[j].p;}
  cb=[l->queue commandBuffer];ce=[cb computeCommandEncoder];[ce setComputePipelineState:zp];[ce setBuffer:routed offset:0 atIndex:0];[ce setBytes:&N2560 length:4 atIndex:1];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  for(uint32_t j=0;j<10;j++){uint64_t E=rp[j].i,gw=E*(uint64_t)640*320*4,gs=E*(uint64_t)640*40*2,dw=E*(uint64_t)2560*80*4,ds=E*(uint64_t)2560*10*2;qn_affine_desc gd={l->expert_gate_w0+gw,l->expert_gate_s0+gs,l->expert_gate_b0+gs,640,2560,64,4},ud={l->expert_up_w0+gw,l->expert_up_s0+gs,l->expert_up_b0+gs,640,2560,64,4},dd={l->expert_down_w0+dw,l->expert_down_s0+ds,l->expert_down_b0+ds,2560,640,64,4};if(!l->expert_cached[E]){if(qn_affine_make_view(l->device,&l->shard9,&gd,&l->expert_gate[E],err,errlen)||qn_affine_make_view(l->device,&l->shard9,&ud,&l->expert_up[E],err,errlen)||qn_affine_make_view(l->device,&l->shard10,&dd,&l->expert_down[E],err,errlen))return -1;l->expert_cached[E]=1;}encode_affine(ce,q4,&l->expert_gate[E],mo,gb,640,2560);encode_affine(ce,q4,&l->expert_up[E],mo,ub,640,2560);[ce setComputePipelineState:sm];[ce setBuffer:gb offset:0 atIndex:0];[ce setBuffer:ub offset:0 atIndex:1];[ce setBuffer:eh offset:0 atIndex:2];[ce setBytes:&N640 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(640,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q4,&l->expert_down[E],eh,db,2560,640);float w=rp[j].p;[ce setComputePipelineState:sa];[ce setBuffer:db offset:0 atIndex:0];[ce setBuffer:routed offset:0 atIndex:1];[ce setBytes:&w length:4 atIndex:2];[ce setBytes:&N2560 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];}
  encode_affine(ce,q8,&l->shared_gate_proj,mo,gb,640,2560);encode_affine(ce,q8,&l->shared_up_proj,mo,ub,640,2560);[ce setComputePipelineState:sm];[ce setBuffer:gb offset:0 atIndex:0];[ce setBuffer:ub offset:0 atIndex:1];[ce setBuffer:eh offset:0 atIndex:2];[ce setBytes:&N640 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(640,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];encode_affine(ce,q8,&l->shared_down_proj,eh,shared,2560,640);[ce setComputePipelineState:bd];[ce setBuffer:l->shared_gate_weight.buffer offset:0 atIndex:0];[ce setBuffer:mo offset:0 atIndex:1];[ce setBuffer:sgate offset:0 atIndex:2];[ce dispatchThreads:MTLSizeMake(32,1,1) threadsPerThreadgroup:MTLSizeMake(32,1,1)];[ce setComputePipelineState:ms];[ce setBuffer:shared offset:0 atIndex:0];[ce setBuffer:sgate offset:0 atIndex:1];[ce setBytes:&N2560 length:4 atIndex:2];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];float one=1.0f;[ce setComputePipelineState:sa];[ce setBuffer:shared offset:0 atIndex:0];[ce setBuffer:routed offset:0 atIndex:1];[ce setBytes:&one length:4 atIndex:2];[ce setBytes:&N2560 length:4 atIndex:3];[ce dispatchThreads:MTLSizeMake(2560,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];
  [ce setComputePipelineState:rip];[ce setBuffer:base offset:0 atIndex:0];[ce setBuffer:routed offset:0 atIndex:1];[ce setBuffer:io offset:0 atIndex:2];[ce setBuffer:finalb offset:0 atIndex:3];[ce dispatchThreads:MTLSizeMake(10240,1,1) threadsPerThreadgroup:MTLSizeMake(256,1,1)];[ce endEncoding];[cb commit];[cb waitUntilCompleted];if(cb.status==MTLCommandBufferStatusError){seterr(err,errlen,cb.error.description.UTF8String);return -1;}memcpy(final_out,finalb.contents,10240*4);if(elapsed)*elapsed=now_ms()-t0;
 }
 return 0;
}

int qn_qwen4_layer_forward_decode(qn_qwen4_layer*l,const qn_qwen4_decode_input*in,qn_qwen4_decode_output*out,char*err,size_t errlen){
 if(!l||!in||!out||!out->hyper_state){seterr(err,errlen,"invalid decode arguments");return -1;}float att_hyper[10240];double ta=0,tm=0,t0=now_ms();if(qn_qwen4_layer_forward_attention(l,in,att_hyper,&ta,err,errlen))return -1;if(out->indexer_raw_key){id<MTLBuffer>b=scratch(l,@"att_idxraw",640*4);memcpy(out->indexer_raw_key,(float*)b.contents+512,128*4);}if(out->key_cache){id<MTLBuffer>b=scratch(l,@"att_kcur",512*4);memcpy(out->key_cache,b.contents,512*4);}if(out->value_cache){id<MTLBuffer>b=scratch(l,@"att_vcur",512*4);memcpy(out->value_cache,b.contents,512*4);}if(qn_run_mlp_full(l,att_hyper,out->hyper_state,out->selected_expert_ids,out->selected_expert_weights,&tm,err,errlen))return -1;out->attention_ms=ta;out->moe_ms=tm;out->total_ms=now_ms()-t0;return 0;
}
void qn_qwen4_layer_close(qn_qwen4_layer*l){if(!l)return;@autoreleasepool{l->scratch=nil;l->pipelines=nil;l->library=nil;l->queue=nil;l->device=nil;}qn_file_map_close(&l->shard8);qn_file_map_close(&l->shard9);qn_file_map_close(&l->shard10);free(l);}
